/**
 * Congressional Research Service (CRS) Policy Areas
 *
 * The 32 official policy area categories used on congress.gov,
 * each with common subtopics for user-friendly selection.
 */

export interface IssueOption {
  label: string;
  category: string;
}

const POLICY_AREAS: Record<string, string[]> = {
  'Agriculture and Food': ['Farming', 'Food Safety', 'SNAP/Food Stamps', 'School Meals', 'Rural Development', 'Farm Subsidies', 'Organic Farming', 'GMOs', 'Agricultural Workers', 'Crop Insurance', 'Farm-to-Table', 'Food Deserts', 'Meat Processing', 'Agricultural Technology', 'Water Rights (Ag)'],
  'Animals': ['Animal Welfare', 'Endangered Species', 'Wildlife', 'Factory Farming', 'Animal Testing', 'Puppy Mills', 'Wildlife Corridors', 'Invasive Species', 'Horse Slaughter', 'Service Animals'],
  'Armed Forces and National Security': ['Veterans', 'Military Funding', 'National Guard', 'Defense Spending', 'VA Healthcare', 'Nuclear Weapons', 'Cybersecurity', 'Military Bases', 'Military Families', 'PTSD', 'Arms Sales', 'Military Housing', 'Drone Warfare', 'Veteran Suicide', 'Military Sexual Assault', 'Gold Star Families', 'Defense Contracts', 'Selective Service', 'Space Force', 'Military Recruitment'],
  'Arts, Culture, Religion': ['Arts Funding', 'Museums', 'Religious Liberty', 'Public Broadcasting', 'Historic Preservation', 'Faith-Based Initiatives', 'Cultural Heritage', 'Libraries', 'NEA/NEH Funding'],
  'Civil Rights and Liberties, Minority Issues': ['Voting Rights', 'Discrimination', 'LGBTQ+ Rights', 'Disability Rights', 'Free Speech', 'Racial Justice', 'Police Accountability', 'Affirmative Action', 'Reparations', 'Censorship', 'DEI', 'Age Discrimination', 'Religious Exemptions', 'Hate Speech', 'Voter Suppression', 'ADA Compliance', 'Equal Pay', 'Indigenous Rights'],
  'Commerce': ['Small Business', 'Consumer Protection', 'Trade', 'Antitrust', 'Gig Economy', 'Supply Chain', 'Price Gouging', 'Junk Fees', 'Price Transparency', 'Shrinkflation', 'Right to Repair', 'Mergers and Acquisitions'],
  'Congress': ['Congressional Reform', 'Term Limits', 'Government Accountability', 'Congressional Oversight', 'Congressional Pay', 'Earmarks', 'Congressional Stock Trading', 'Insider Trading Ban', 'Congressional Subpoena Power'],
  'Crime and Law Enforcement': ['Gun Violence', 'Police Reform', 'Drug Policy', 'Criminal Justice Reform', 'Sentencing', 'Fentanyl', 'Human Trafficking', 'Cybercrime', 'Domestic Violence', 'Hate Crimes', 'Mass Incarceration', 'Death Penalty', 'Bail Reform', 'Juvenile Justice', 'Gang Violence', 'Recidivism', 'Carjacking', 'Retail Theft', 'Cyberstalking', 'School Shootings', 'Sex Trafficking', 'Elder Abuse', 'White Collar Crime', 'Asset Forfeiture', 'Body Cameras', 'Drug Cartels', 'Organized Crime'],
  'Economics and Public Finance': ['Federal Budget', 'National Debt', 'Inflation', 'Cost of Living', 'Wage Growth', 'Federal Reserve', 'Recession', 'Trade Deficit', 'Income Inequality', 'Poverty Rate', 'GDP Growth', 'Government Shutdown', 'Debt Ceiling', 'Austerity', 'Grocery Prices', 'Gas Prices', 'Utility Bills', 'Rent Prices'],
  'Education': ['K-12 Education', 'Student Loans', 'Higher Education', 'Special Education', 'School Choice', 'Teacher Pay', 'School Safety', 'Book Bans', 'School Funding', 'Early Childhood Education', 'Pre-K', 'Title IX', 'STEM Education', 'Homeschooling', 'Charter Schools', 'Student Debt Forgiveness', 'School Vouchers', 'Standardized Testing', 'College Affordability', 'Sex Education', 'Library Funding', 'Civics Education', 'School Boards', 'Bullying'],
  'Emergency Management': ['Disaster Relief', 'FEMA', 'Emergency Preparedness', 'Climate Resilience', 'Pandemic Preparedness', 'First Responders', 'Wildfire Management', 'Flood Insurance', 'National Stockpile', 'Climate Adaptation'],
  'Energy': ['Oil and Gas', 'Renewable Energy', 'Energy Costs', 'Nuclear Energy', 'Electric Vehicles', 'Energy Grid', 'Fracking', 'Carbon Tax', 'Energy Storage', 'Hydrogen', 'Pipeline Safety', 'Energy Independence', 'Geothermal', 'Offshore Wind', 'Coal'],
  'Environmental Protection': ['Climate Change', 'Clean Air', 'Clean Water', 'Pollution', 'EPA', 'PFAS/Forever Chemicals', 'Plastics', 'Environmental Justice', 'Wildfires', 'Carbon Capture', 'Methane', 'NEPA Reform', 'Deforestation', 'Microplastics', 'Lead Pipes', 'Superfund Sites', 'Ozone', 'Wetlands'],
  'Families': ['Child Care', 'Paid Family Leave', 'Child Welfare', 'Foster Care', 'Adoption', 'Child Tax Credit', 'Parental Rights', 'Child Safety Online', 'Child Poverty', 'Grandparent Caregivers', 'Youth Mental Health', 'Social Media Age Limits', 'Screen Time', 'Grandparent Rights', 'Surrogacy', 'Fertility Treatment', 'Single Parents', 'Child Hunger'],
  'Finance and Financial Sector': ['Banking', 'Credit', 'Wall Street Regulation', 'Cryptocurrency', 'Predatory Lending', 'Insurance Regulation', 'Financial Literacy', 'Student Debt', 'Bank Failures', 'FDIC', 'Credit Card Fees', 'Buy Now Pay Later', 'Credit Scores', 'Fintech', 'Money Laundering', 'SEC Regulation'],
  'Foreign Trade and International Finance': ['Tariffs', 'Trade Agreements', 'Sanctions', 'Imports/Exports', 'Trade with China', 'USMCA', 'Currency Manipulation', 'Supply Chain Security', 'De-dollarization', 'Export Controls', 'Rare Earth Minerals', 'Forced Labor Imports', 'Trade Enforcement'],
  'Government Operations and Politics': ['Elections', 'Campaign Finance', 'Government Spending', 'Federal Agencies', 'Voter ID', 'Redistricting', 'Ethics Reform', 'Lobbying Reform', 'Government Transparency', 'Filibuster Reform', 'Dark Money', 'Ranked Choice Voting', 'Statehood (DC/PR)', 'Electoral College', 'Term Limits (State)', 'Mail-In Voting', 'Poll Access', 'Government Efficiency', 'DOGE', 'Government Waste'],
  'Health': ['Medicare', 'Medicaid', 'Prescription Drug Costs', 'Mental Health', 'Reproductive Health', 'Opioids', 'ACA/Obamacare', 'Public Health', 'Telehealth', 'Hospital Access', 'Veterans Health', 'Infant/Early Childhood Mental Health', 'Maternal Health', 'Dental Care', 'Long-Term Care', 'Nursing Shortage', 'Vaccine Policy', 'Health Equity', 'Insulin Pricing', 'Gender-Affirming Care', 'Drug Importation', 'Medical Debt', 'Rural Hospitals', 'Obesity', 'Cancer Research', 'Rare Diseases', 'Organ Donation', 'Hearing Aids', 'Vision Care', 'Addiction Treatment', 'Fetal Health', 'Prior Authorization', 'Drug Overdose', 'ER Wait Times', 'Health Insurance Costs'],
  'Housing and Community Development': ['Affordable Housing', 'Homelessness', 'Rent', 'Mortgage Rates', 'HUD', 'Zoning Reform', 'Public Housing', 'Housing Discrimination', 'Rent Control', 'First-Time Homebuyers', 'Housing Supply', 'Gentrification', 'Lead Paint', 'Eviction Protections', 'Down Payment Assistance', 'NIMBY/Zoning'],
  'Immigration': ['Border Security', 'DACA', 'Visas', 'Asylum', 'Refugee Policy', 'Legal Immigration', 'Immigration Courts', 'H-1B Visas', 'Citizenship', 'Deportation', 'TPS', 'E-Verify', 'Immigration Detention', 'Family Separation', 'Sanctuary Cities', 'Immigration Backlog', 'Work Permits', 'Birthright Citizenship', 'Immigration Raids', 'Migrant Workers'],
  'International Affairs': ['Foreign Aid', 'Diplomacy', 'NATO', 'Middle East', 'Ukraine', 'China', 'Iran', 'Israel/Palestine', 'Russia', 'Taiwan', 'North Korea', 'Africa', 'Latin America', 'United Nations', 'Human Rights Abroad', 'Arms Control', 'Terrorism', 'South Korea', 'India', 'Venezuela', 'Sanctions Enforcement', 'Global Health', 'WHO', 'Peacekeeping', 'Cybersecurity (Intl)', 'Climate Agreements', 'Trade War'],
  'Labor and Employment': ['Minimum Wage', 'Worker Rights', 'Unions', 'Workplace Safety', 'Unemployment', 'Paid Sick Leave', 'Remote Work', 'Overtime Pay', 'Child Labor', 'Pension', 'Right to Work', 'Gig Worker Benefits', 'Workplace Harassment', 'Tipped Minimum Wage', 'Non-Compete Agreements', 'Apprenticeships', 'Worker Misclassification', 'Four-Day Work Week', 'Prevailing Wage'],
  'Law': ['Supreme Court', 'Judicial Appointments', 'Legal Reform', 'Court Reform', 'Legal Aid', 'Civil Asset Forfeiture', 'Qualified Immunity', 'Mandatory Minimums', 'Privacy Law', 'Eminent Domain', 'Class Action Reform', 'Wrongful Conviction'],
  'Native Americans': ['Tribal Sovereignty', 'Indian Health Service', 'Native Land Rights', 'Missing and Murdered Indigenous People', 'Tribal Education', 'Tribal Gaming', 'Water Rights (Tribal)', 'Language Preservation', 'Urban Indigenous Issues'],
  'Public Lands and Natural Resources': ['National Parks', 'Public Lands', 'Mining', 'Forestry', 'Conservation', 'Wilderness Protection', 'Drilling on Public Lands', 'Offshore Drilling', 'Critical Minerals', 'Grazing Rights', 'Water Allocation', 'Endangered Habitat', 'Old Growth Forests'],
  'Science, Technology, Communications': ['AI', 'Internet/Broadband', 'Space', 'Social Media Regulation', 'Data Privacy', 'Cybersecurity', 'Net Neutrality', 'Tech Monopolies', 'Automation/Robotics', 'Deepfakes', 'Age Verification', 'Semiconductors/CHIPS', 'Autonomous Vehicles', 'Quantum Computing', '5G/6G', 'Open Source', 'Surveillance Technology', 'Algorithmic Bias', 'Right to Repair (Tech)', 'TikTok Ban', 'Phone Addiction'],
  'Social Welfare': ['Social Security', 'Poverty', 'Disability Benefits', 'Safety Net Programs', 'Universal Basic Income', 'Food Insecurity', 'Senior Care', 'Aging', 'Section 8/Housing Vouchers', 'TANF', 'WIC', 'SSI', 'SSDI', 'Supplemental Nutrition', 'Community Health Centers', 'Warming/Cooling Centers'],
  'Sports and Recreation': ['Youth Sports', 'Outdoor Recreation', 'Stadium Funding', 'Title IX Athletics', 'Recreation Access', 'Olympic Funding', 'NIL/College Athletes', 'Youth Sports Safety'],
  'Taxation': ['Income Tax', 'Corporate Tax', 'Tax Reform', 'Tax Credits', 'Capital Gains Tax', 'Wealth Tax', 'Estate Tax', 'Tax Loopholes', 'Property Tax', 'Sales Tax', 'Carbon Tax', 'Crypto Tax', 'SALT Deduction', 'Tax Filing Simplification', 'Charitable Deduction'],
  'Transportation and Public Works': ['Roads', 'Public Transit', 'Airports', 'Rail', 'Infrastructure', 'High-Speed Rail', 'Highway Safety', 'Trucking', 'EV Charging Infrastructure', 'Airline Consumer Protection', 'Bike Infrastructure', 'Pedestrian Safety', 'Autonomous Vehicles', 'Speed Cameras', 'Bridge Safety', 'Port Infrastructure', 'Last Mile Delivery'],
  'Water Resources Development': ['Dams', 'Flood Control', 'Water Infrastructure', 'Drought', 'Clean Drinking Water', 'Water Rights', 'Desalination', 'PFAS in Water', 'Stormwater Management', 'Levee Repair', 'Great Lakes', 'Colorado River'],
};

// Keyword synonyms: common words people type → terms that match our labels/categories
const KEYWORD_ALIASES: Record<string, string[]> = {
  'guns': ['gun violence', 'crime and law enforcement'],
  'gun': ['gun violence', 'crime and law enforcement'],
  'firearms': ['gun violence', 'crime and law enforcement'],
  'shooting': ['gun violence', 'crime and law enforcement'],
  'second amendment': ['gun violence', 'crime and law enforcement'],
  '2a': ['gun violence', 'crime and law enforcement'],
  'taxes': ['taxation', 'income tax', 'tax reform'],
  'tax': ['taxation', 'income tax', 'tax reform'],
  'irs': ['taxation', 'income tax'],
  'roads': ['roads', 'infrastructure', 'transportation'],
  'highways': ['roads', 'infrastructure', 'transportation'],
  'bridges': ['infrastructure', 'transportation'],
  'potholes': ['roads', 'infrastructure'],
  'traffic': ['roads', 'public transit', 'transportation'],
  'train': ['rail', 'public transit'],
  'trains': ['rail', 'public transit'],
  'subway': ['public transit', 'transportation'],
  'bus': ['public transit', 'transportation'],
  'doctor': ['health', 'medicare', 'medicaid'],
  'doctors': ['health', 'medicare', 'medicaid'],
  'hospital': ['health', 'medicare', 'prescription drug costs'],
  'insurance': ['health', 'aca/obamacare', 'medicare'],
  'medicine': ['prescription drug costs', 'health'],
  'drugs': ['drug policy', 'prescription drug costs', 'opioids'],
  'opioid': ['opioids', 'drug policy'],
  'abortion': ['reproductive health', 'health'],
  'roe': ['reproductive health', 'health'],
  'pro-choice': ['reproductive health', 'health'],
  'pro-life': ['reproductive health', 'health'],
  'school': ['k-12 education', 'education', 'school choice'],
  'schools': ['k-12 education', 'education', 'school choice'],
  'college': ['higher education', 'student loans'],
  'university': ['higher education', 'student loans'],
  'tuition': ['higher education', 'student loans'],
  'loans': ['student loans', 'credit'],
  'debt': ['national debt', 'student loans'],
  'jobs': ['labor and employment', 'minimum wage', 'unemployment'],
  'job': ['labor and employment', 'unemployment'],
  'work': ['labor and employment', 'worker rights'],
  'wages': ['minimum wage', 'labor and employment'],
  'salary': ['minimum wage', 'labor and employment'],
  'pay': ['minimum wage', 'labor and employment'],
  'union': ['unions', 'labor and employment'],
  'rent': ['rent', 'affordable housing'],
  'renting': ['rent', 'affordable housing'],
  'apartment': ['rent', 'affordable housing', 'housing'],
  'house': ['affordable housing', 'mortgage rates', 'housing'],
  'mortgage': ['mortgage rates', 'housing'],
  'homeless': ['homelessness', 'housing'],
  'climate': ['climate change', 'environmental protection'],
  'warming': ['climate change', 'environmental protection'],
  'weather': ['climate change', 'environmental protection'],
  'pollution': ['pollution', 'clean air', 'clean water'],
  'carbon': ['climate change', 'clean air'],
  'solar': ['renewable energy', 'energy'],
  'wind': ['renewable energy', 'energy'],
  'electric': ['renewable energy', 'energy costs'],
  'gas': ['oil and gas', 'energy costs'],
  'oil': ['oil and gas', 'energy'],
  'border': ['border security', 'immigration'],
  'immigrants': ['immigration', 'daca', 'asylum'],
  'immigrant': ['immigration', 'daca', 'asylum'],
  'undocumented': ['immigration', 'daca'],
  'deportation': ['deportation', 'immigration', 'border security'],
  'deport': ['deportation', 'immigration', 'border security'],
  'wall': ['border security', 'immigration'],
  'refugee': ['refugee policy', 'asylum', 'immigration'],
  'refugees': ['refugee policy', 'asylum', 'immigration'],
  'welfare': ['social welfare', 'safety net programs', 'snap/food stamps'],
  'food stamps': ['snap/food stamps', 'agriculture and food'],
  'snap': ['snap/food stamps', 'agriculture and food'],
  'social security': ['social security', 'social welfare'],
  'retirement': ['social security', 'social welfare'],
  'medicare': ['medicare', 'health'],
  'medicaid': ['medicaid', 'health'],
  'veteran': ['veterans', 'armed forces and national security'],
  'vets': ['veterans', 'armed forces and national security'],
  'military': ['military funding', 'defense spending', 'armed forces'],
  'army': ['military funding', 'armed forces and national security'],
  'navy': ['military funding', 'armed forces and national security'],
  'war': ['armed forces and national security', 'foreign aid'],
  'police': ['police reform', 'crime and law enforcement'],
  'cops': ['police reform', 'crime and law enforcement'],
  'prison': ['criminal justice reform', 'sentencing'],
  'jail': ['criminal justice reform', 'sentencing'],
  'crime': ['crime and law enforcement', 'criminal justice reform'],
  'weed': ['drug policy', 'crime and law enforcement'],
  'marijuana': ['drug policy', 'crime and law enforcement'],
  'cannabis': ['drug policy', 'crime and law enforcement'],
  'crypto': ['cryptocurrency', 'finance and financial sector'],
  'bitcoin': ['cryptocurrency', 'finance and financial sector'],
  'banks': ['banking', 'finance and financial sector'],
  'wall street': ['wall street regulation', 'finance'],
  'internet': ['internet/broadband', 'science, technology'],
  'broadband': ['internet/broadband', 'science, technology'],
  'wifi': ['internet/broadband', 'science, technology'],
  'privacy': ['data privacy', 'science, technology'],
  'tiktok': ['social media regulation', 'data privacy'],
  'social media': ['social media regulation', 'data privacy'],
  'ai': ['ai', 'science, technology'],
  'artificial intelligence': ['ai', 'science, technology'],
  'tariff': ['tariffs', 'foreign trade'],
  'tariffs': ['tariffs', 'foreign trade'],
  'trade': ['trade', 'trade agreements', 'foreign trade'],
  'china': ['china', 'international affairs', 'tariffs'],
  'ukraine': ['ukraine', 'international affairs', 'foreign aid'],
  'israel': ['israel/palestine', 'middle east', 'international affairs', 'foreign aid'],
  'palestine': ['israel/palestine', 'middle east', 'international affairs'],
  'gaza': ['israel/palestine', 'middle east', 'international affairs'],
  'nato': ['nato', 'international affairs'],
  'voting': ['voting rights', 'elections'],
  'vote': ['voting rights', 'elections'],
  'election': ['elections', 'campaign finance'],
  'gerrymandering': ['elections', 'voting rights'],
  'lgbtq': ['lgbtq+ rights', 'civil rights'],
  'gay': ['lgbtq+ rights', 'civil rights'],
  'trans': ['lgbtq+ rights', 'civil rights'],
  'transgender': ['lgbtq+ rights', 'civil rights'],
  'discrimination': ['discrimination', 'civil rights'],
  'racism': ['discrimination', 'civil rights'],
  'disability': ['disability rights', 'disability benefits'],
  'disabled': ['disability rights', 'disability benefits'],
  'childcare': ['child care', 'families'],
  'daycare': ['child care', 'families'],
  'parental leave': ['paid family leave', 'families'],
  'maternity': ['paid family leave', 'families'],
  'paternity': ['paid family leave', 'families'],
  'parks': ['national parks', 'public lands'],
  'forest': ['forestry', 'public lands'],
  'water': ['clean water', 'water infrastructure'],
  'flood': ['flood control', 'disaster relief'],
  'hurricane': ['disaster relief', 'fema', 'emergency management'],
  'tornado': ['disaster relief', 'fema', 'emergency management'],
  'earthquake': ['disaster relief', 'fema'],
  'fema': ['fema', 'disaster relief', 'emergency management'],
  'inflation': ['inflation', 'cost of living', 'economics'],
  'prices': ['inflation', 'cost of living'],
  'expensive': ['inflation', 'cost of living'],
  'groceries': ['inflation', 'cost of living', 'snap/food stamps'],
  'farm': ['farming', 'agriculture and food'],
  'farmer': ['farming', 'agriculture and food'],
  'food': ['food safety', 'snap/food stamps', 'school meals'],
  'animals': ['animal welfare', 'endangered species'],
  'pets': ['animal welfare', 'animals'],
  'space': ['space', 'science, technology'],
  'nasa': ['space', 'science, technology'],
  'nuclear': ['nuclear energy', 'nuclear weapons', 'energy'],
  'corruption': ['government accountability', 'campaign finance'],
  'congress': ['congressional reform', 'term limits'],
  'term limits': ['term limits', 'congressional reform'],
  'supreme court': ['supreme court', 'judicial appointments'],
  'scotus': ['supreme court', 'judicial appointments'],
  'judges': ['judicial appointments', 'supreme court'],
  // International affairs
  'iran': ['iran', 'international affairs'],
  'tehran': ['iran', 'international affairs'],
  'hamas': ['israel/palestine', 'middle east'],
  'hezbollah': ['middle east', 'international affairs'],
  'netanyahu': ['israel/palestine', 'international affairs'],
  'russia': ['russia', 'international affairs'],
  'putin': ['russia', 'international affairs'],
  'taiwan': ['taiwan', 'international affairs', 'china'],
  'north korea': ['north korea', 'international affairs'],
  'kim jong': ['north korea', 'international affairs'],
  // Crime
  'fentanyl': ['fentanyl', 'drug policy', 'crime and law enforcement'],
  'trafficking': ['human trafficking', 'crime and law enforcement'],
  // Cybersecurity
  'cybersecurity': ['cybersecurity', 'science, technology', 'armed forces and national security'],
  'hack': ['cybersecurity', 'cybercrime'],
  'hacking': ['cybersecurity', 'cybercrime'],
  // Energy & environment
  'electric vehicle': ['electric vehicles', 'energy'],
  'ev': ['electric vehicles', 'energy'],
  'tesla': ['electric vehicles', 'energy'],
  'pfas': ['pfas/forever chemicals', 'environmental protection'],
  'fracking': ['fracking', 'energy'],
  'wildfire': ['wildfires', 'environmental protection'],
  'wildfires': ['wildfires', 'environmental protection'],
  // Education
  'teacher': ['teacher pay', 'education'],
  'book ban': ['book bans', 'education'],
  'book bans': ['book bans', 'education'],
  // Commerce & economy
  'gig': ['gig economy', 'commerce'],
  'uber': ['gig economy', 'worker rights'],
  'lyft': ['gig economy', 'worker rights'],
  // Housing
  'zoning': ['zoning reform', 'housing and community development'],
  // Taxation
  'wealth tax': ['wealth tax', 'taxation'],
  'billionaire': ['wealth tax', 'taxation'],
  'billionaires': ['wealth tax', 'taxation'],
  // Health - new
  'iecmh': ['infant/early childhood mental health', 'mental health', 'health'],
  'infant mental health': ['infant/early childhood mental health', 'health'],
  'maternal': ['maternal health', 'reproductive health', 'health'],
  'pregnancy': ['maternal health', 'reproductive health'],
  'postpartum': ['maternal health', 'health'],
  'dentist': ['dental care', 'health'],
  'dental': ['dental care', 'health'],
  'nurse': ['nursing shortage', 'health'],
  'nurses': ['nursing shortage', 'health'],
  'nursing': ['nursing shortage', 'long-term care', 'health'],
  'vaccine': ['vaccine policy', 'public health'],
  'vaccines': ['vaccine policy', 'public health'],
  'vaccination': ['vaccine policy', 'public health'],
  'telehealth': ['telehealth', 'health'],
  'long-term care': ['long-term care', 'senior care'],
  'elderly': ['senior care', 'aging', 'long-term care'],
  'seniors': ['senior care', 'aging', 'social security'],
  // Crime & justice - new
  'incarceration': ['mass incarceration', 'criminal justice reform'],
  'death penalty': ['death penalty', 'sentencing'],
  'execution': ['death penalty', 'sentencing'],
  'bail': ['bail reform', 'criminal justice reform'],
  'juvenile': ['juvenile justice', 'crime and law enforcement'],
  'youth crime': ['juvenile justice', 'gang violence'],
  'gang': ['gang violence', 'crime and law enforcement'],
  'gangs': ['gang violence', 'crime and law enforcement'],
  'recidivism': ['recidivism', 'criminal justice reform'],
  'reentry': ['recidivism', 'criminal justice reform'],
  // Education - new
  'pre-k': ['pre-k', 'early childhood education'],
  'preschool': ['pre-k', 'early childhood education'],
  'title ix': ['title ix', 'education'],
  'stem': ['stem education', 'education'],
  'homeschool': ['homeschooling', 'education'],
  'homeschooling': ['homeschooling', 'education'],
  // Civil rights - new
  'racial justice': ['racial justice', 'discrimination'],
  'blm': ['racial justice', 'police accountability'],
  'affirmative action': ['affirmative action', 'civil rights'],
  'reparations': ['reparations', 'racial justice'],
  'censorship': ['censorship', 'free speech'],
  // Labor - new
  'sick leave': ['paid sick leave', 'labor and employment'],
  'remote work': ['remote work', 'labor and employment'],
  'overtime': ['overtime pay', 'labor and employment'],
  'child labor': ['child labor', 'labor and employment'],
  'pension': ['pension', 'social security'],
  'pensions': ['pension', 'social security'],
  '401k': ['pension', 'finance and financial sector'],
  // Government - new
  'voter id': ['voter id', 'elections', 'voting rights'],
  'redistricting': ['redistricting', 'elections'],
  'lobbying': ['lobbying reform', 'ethics reform'],
  'lobbyist': ['lobbying reform', 'government operations'],
  'filibuster': ['filibuster reform', 'congressional reform'],
  'transparency': ['government transparency', 'government operations'],
  'ethics': ['ethics reform', 'government operations'],
  // Social welfare - new
  'ubi': ['universal basic income', 'social welfare'],
  'basic income': ['universal basic income', 'social welfare'],
  'food insecurity': ['food insecurity', 'snap/food stamps'],
  'hungry': ['food insecurity', 'snap/food stamps'],
  'hunger': ['food insecurity', 'snap/food stamps'],
  'aging': ['aging', 'senior care', 'social welfare'],
  // Agriculture - new
  'gmo': ['gmos', 'food safety'],
  'gmos': ['gmos', 'food safety', 'agriculture and food'],
  'organic': ['organic farming', 'agriculture and food'],
  'crop': ['crop insurance', 'farming'],
  'subsidy': ['farm subsidies', 'agriculture and food'],
  'subsidies': ['farm subsidies', 'agriculture and food'],
  // Animals - new
  'factory farm': ['factory farming', 'animal welfare'],
  'animal testing': ['animal testing', 'animal welfare'],
  'puppy mill': ['puppy mills', 'animal welfare'],
  // Law - new
  'court reform': ['court reform', 'supreme court'],
  'court packing': ['court reform', 'supreme court'],
  'legal aid': ['legal aid', 'law'],
  'forfeiture': ['civil asset forfeiture', 'law'],
  // Emergency - new
  'pandemic': ['pandemic preparedness', 'public health'],
  'first responder': ['first responders', 'emergency management'],
  'first responders': ['first responders', 'emergency management'],
  'firefighter': ['first responders', 'emergency management'],
  'paramedic': ['first responders', 'emergency management'],
  // Native Americans - new
  'mmiw': ['missing and murdered indigenous people', 'native americans'],
  'mmip': ['missing and murdered indigenous people', 'native americans'],
  'indigenous': ['native americans', 'tribal sovereignty'],
  // Public lands - new
  'conservation': ['conservation', 'public lands'],
  'wilderness': ['wilderness protection', 'public lands'],
  'drilling': ['drilling on public lands', 'oil and gas'],
  // Transportation - new
  'high-speed rail': ['high-speed rail', 'rail', 'transportation'],
  'amtrak': ['rail', 'high-speed rail', 'transportation'],
  'trucking': ['trucking', 'transportation'],
  'ev charging': ['ev charging infrastructure', 'electric vehicles'],
  // Families - new
  'youth mental health': ['youth mental health', 'mental health', 'families'],
  // International - new
  'terrorism': ['terrorism', 'armed forces and national security'],
  'arms control': ['arms control', 'nuclear weapons'],
  'human rights': ['human rights abroad', 'international affairs'],
  // Finance - new
  'payday loan': ['predatory lending', 'finance and financial sector'],
  'payday': ['predatory lending', 'finance and financial sector'],
  'student debt': ['student debt', 'student loans'],
  // Health - expanded
  'insulin': ['insulin pricing', 'prescription drug costs', 'health'],
  'drug prices': ['prescription drug costs', 'drug importation', 'health'],
  'medical debt': ['medical debt', 'health'],
  'hospital bills': ['medical debt', 'hospital access', 'health'],
  'rural hospital': ['rural hospitals', 'hospital access', 'health'],
  'gender affirming': ['gender-affirming care', 'health'],
  'therapy': ['mental health', 'addiction treatment', 'health'],
  'cancer': ['cancer research', 'health'],
  'obesity': ['obesity', 'public health', 'health'],
  'weight': ['obesity', 'health'],
  'hearing aid': ['hearing aids', 'health'],
  'hearing aids': ['hearing aids', 'health'],
  'vision': ['vision care', 'health'],
  'eye care': ['vision care', 'health'],
  'organ donor': ['organ donation', 'health'],
  'organ donation': ['organ donation', 'health'],
  'rare disease': ['rare diseases', 'health'],
  'prior auth': ['prior authorization', 'health'],
  'prior authorization': ['prior authorization', 'health'],
  'addiction': ['addiction treatment', 'opioids', 'health'],
  'rehab': ['addiction treatment', 'health'],
  'rehabilitation': ['addiction treatment', 'health'],
  'fetal': ['fetal health', 'reproductive health', 'health'],
  'prenatal': ['fetal health', 'maternal health', 'health'],
  // Tech - expanded
  'semiconductors': ['semiconductors/chips', 'science, technology'],
  'chips': ['semiconductors/chips', 'science, technology'],
  'deepfake': ['deepfakes', 'science, technology'],
  'deepfakes': ['deepfakes', 'science, technology'],
  'age verification': ['age verification', 'science, technology'],
  'self driving': ['autonomous vehicles', 'science, technology', 'transportation'],
  'autonomous': ['autonomous vehicles', 'science, technology', 'transportation'],
  'quantum': ['quantum computing', 'science, technology'],
  '5g': ['5g/6g', 'science, technology'],
  '6g': ['5g/6g', 'science, technology'],
  'surveillance': ['surveillance technology', 'data privacy', 'science, technology'],
  'algorithm': ['algorithmic bias', 'science, technology'],
  'right to repair': ['right to repair', 'right to repair (tech)', 'commerce', 'science, technology'],
  'repair': ['right to repair', 'right to repair (tech)'],
  // Immigration - expanded
  'tps': ['tps', 'immigration'],
  'green card': ['legal immigration', 'visas', 'immigration'],
  'visa backlog': ['immigration backlog', 'visas', 'immigration'],
  'e-verify': ['e-verify', 'immigration'],
  'ice': ['immigration detention', 'deportation', 'immigration'],
  'detention': ['immigration detention', 'immigration'],
  'family separation': ['family separation', 'immigration'],
  'sanctuary': ['sanctuary cities', 'immigration'],
  'work permit': ['work permits', 'immigration'],
  'birthright': ['birthright citizenship', 'immigration'],
  // Commerce - expanded
  'junk fees': ['junk fees', 'consumer protection', 'commerce'],
  'hidden fees': ['junk fees', 'consumer protection', 'commerce'],
  'shrinkflation': ['shrinkflation', 'consumer protection', 'commerce'],
  'merger': ['mergers and acquisitions', 'antitrust', 'commerce'],
  'antitrust': ['antitrust', 'mergers and acquisitions', 'commerce'],
  // Civil Rights - expanded
  'dei': ['dei', 'civil rights and liberties, minority issues'],
  'diversity': ['dei', 'civil rights and liberties, minority issues'],
  'age discrimination': ['age discrimination', 'civil rights and liberties, minority issues'],
  'ageism': ['age discrimination', 'civil rights and liberties, minority issues'],
  'religious freedom': ['religious exemptions', 'religious liberty', 'civil rights'],
  'religious exemption': ['religious exemptions', 'civil rights and liberties, minority issues'],
  'voter suppression': ['voter suppression', 'voting rights', 'civil rights'],
  'equal pay': ['equal pay', 'civil rights and liberties, minority issues'],
  'pay gap': ['equal pay', 'civil rights and liberties, minority issues'],
  'ada': ['ada compliance', 'disability rights', 'civil rights'],
  'hate speech': ['hate speech', 'free speech', 'civil rights'],
  // Finance - expanded
  'fdic': ['fdic', 'bank failures', 'finance and financial sector'],
  'credit card': ['credit card fees', 'finance and financial sector'],
  'credit cards': ['credit card fees', 'finance and financial sector'],
  'bnpl': ['buy now pay later', 'finance and financial sector'],
  'buy now pay later': ['buy now pay later', 'finance and financial sector'],
  'bank failure': ['bank failures', 'fdic', 'finance and financial sector'],
  'credit score': ['credit scores', 'finance and financial sector'],
  'fintech': ['fintech', 'finance and financial sector'],
  'sec': ['sec regulation', 'wall street regulation', 'finance and financial sector'],
  'money laundering': ['money laundering', 'finance and financial sector'],
  'aml': ['money laundering', 'finance and financial sector'],
  // Social Welfare - expanded
  'section 8': ['section 8/housing vouchers', 'social welfare'],
  'housing voucher': ['section 8/housing vouchers', 'social welfare'],
  'wic': ['wic', 'social welfare', 'food insecurity'],
  'tanf': ['tanf', 'social welfare'],
  'ssi': ['ssi', 'disability benefits', 'social welfare'],
  'ssdi': ['ssdi', 'disability benefits', 'social welfare'],
  'community health': ['community health centers', 'social welfare', 'health'],
  // Government - expanded
  'stock trading': ['congressional stock trading', 'congress'],
  'congressional trading': ['congressional stock trading', 'congress'],
  'earmark': ['earmarks', 'congress'],
  'earmarks': ['earmarks', 'congress'],
  'dark money': ['dark money', 'campaign finance', 'government operations'],
  'ranked choice': ['ranked choice voting', 'elections', 'government operations'],
  'rcv': ['ranked choice voting', 'elections'],
  'statehood': ['statehood (dc/pr)', 'government operations'],
  'dc statehood': ['statehood (dc/pr)', 'government operations'],
  'puerto rico': ['statehood (dc/pr)', 'latin america'],
  'electoral college': ['electoral college', 'elections', 'government operations'],
  'mail-in': ['mail-in voting', 'elections', 'government operations'],
  'absentee': ['mail-in voting', 'elections'],
  'poll': ['poll access', 'elections', 'government operations'],
  // Arts - expanded
  'pbs': ['public broadcasting', 'arts, culture, religion'],
  'npr': ['public broadcasting', 'arts, culture, religion'],
  'public broadcasting': ['public broadcasting', 'arts, culture, religion'],
  'nea': ['nea/neh funding', 'arts funding', 'arts, culture, religion'],
  'neh': ['nea/neh funding', 'arts, culture, religion'],
  'library': ['libraries', 'library funding'],
  'libraries': ['libraries', 'library funding'],
  'museum': ['museums', 'arts, culture, religion'],
  'museums': ['museums', 'arts, culture, religion'],
  'historic preservation': ['historic preservation', 'arts, culture, religion'],
  // Environment - expanded
  'carbon capture': ['carbon capture', 'environmental protection'],
  'methane': ['methane', 'environmental protection'],
  'nepa': ['nepa reform', 'environmental protection'],
  'microplastics': ['microplastics', 'plastics', 'environmental protection'],
  'microplastic': ['microplastics', 'plastics', 'environmental protection'],
  'lead pipes': ['lead pipes', 'clean water', 'environmental protection'],
  'lead pipe': ['lead pipes', 'clean water', 'environmental protection'],
  'superfund': ['superfund sites', 'environmental protection'],
  'wetlands': ['wetlands', 'environmental protection'],
  'ozone': ['ozone', 'clean air', 'environmental protection'],
  // Energy - expanded
  'hydrogen': ['hydrogen', 'energy'],
  'battery': ['energy storage', 'energy'],
  'batteries': ['energy storage', 'energy'],
  'energy storage': ['energy storage', 'energy'],
  'geothermal': ['geothermal', 'renewable energy', 'energy'],
  'offshore wind': ['offshore wind', 'renewable energy', 'energy'],
  'coal': ['coal', 'energy'],
  'pipeline': ['pipeline safety', 'oil and gas', 'energy'],
  // Housing - expanded
  'rent control': ['rent control', 'rent', 'housing and community development'],
  'first time homebuyer': ['first-time homebuyers', 'housing and community development'],
  'first-time homebuyer': ['first-time homebuyers', 'housing and community development'],
  'nimby': ['nimby/zoning', 'zoning reform', 'housing and community development'],
  'yimby': ['nimby/zoning', 'zoning reform', 'housing and community development'],
  'gentrification': ['gentrification', 'housing and community development'],
  'eviction': ['eviction protections', 'housing and community development'],
  'lead paint': ['lead paint', 'housing and community development'],
  'down payment': ['down payment assistance', 'first-time homebuyers', 'housing'],
  // Crime - expanded
  'carjacking': ['carjacking', 'crime and law enforcement'],
  'carjack': ['carjacking', 'crime and law enforcement'],
  'shoplifting': ['retail theft', 'crime and law enforcement'],
  'retail theft': ['retail theft', 'crime and law enforcement'],
  'stalking': ['cyberstalking', 'domestic violence', 'crime and law enforcement'],
  'cyberstalking': ['cyberstalking', 'crime and law enforcement'],
  'school shooting': ['school shootings', 'gun violence', 'crime and law enforcement'],
  'sex trafficking': ['sex trafficking', 'human trafficking', 'crime and law enforcement'],
  'elder abuse': ['elder abuse', 'crime and law enforcement'],
  'white collar': ['white collar crime', 'crime and law enforcement'],
  'body camera': ['body cameras', 'police reform', 'crime and law enforcement'],
  'body cameras': ['body cameras', 'police reform', 'crime and law enforcement'],
  'body cam': ['body cameras', 'police reform', 'crime and law enforcement'],
  // Transportation - expanded
  'airline': ['airline consumer protection', 'transportation'],
  'airlines': ['airline consumer protection', 'transportation'],
  'flight': ['airline consumer protection', 'airports', 'transportation'],
  'flights': ['airline consumer protection', 'airports', 'transportation'],
  'bike lane': ['bike infrastructure', 'transportation'],
  'bike lanes': ['bike infrastructure', 'transportation'],
  'pedestrian': ['pedestrian safety', 'transportation'],
  'speed camera': ['speed cameras', 'transportation'],
  'bridge': ['bridge safety', 'infrastructure', 'transportation'],
  'port': ['port infrastructure', 'transportation'],
  'ports': ['port infrastructure', 'transportation'],
  // Labor - expanded
  'non-compete': ['non-compete agreements', 'labor and employment'],
  'noncompete': ['non-compete agreements', 'labor and employment'],
  'apprentice': ['apprenticeships', 'labor and employment'],
  'apprenticeship': ['apprenticeships', 'labor and employment'],
  'four day work week': ['four-day work week', 'labor and employment'],
  '4 day work week': ['four-day work week', 'labor and employment'],
  'gig worker': ['gig worker benefits', 'gig economy', 'labor and employment'],
  'freelance': ['gig worker benefits', 'gig economy', 'labor and employment'],
  'freelancer': ['gig worker benefits', 'gig economy', 'labor and employment'],
  'harassment': ['workplace harassment', 'labor and employment'],
  'workplace harassment': ['workplace harassment', 'labor and employment'],
  'tipped wage': ['tipped minimum wage', 'minimum wage', 'labor and employment'],
  'tipped workers': ['tipped minimum wage', 'labor and employment'],
  'misclassification': ['worker misclassification', 'labor and employment'],
  // Law - expanded
  'qualified immunity': ['qualified immunity', 'police reform', 'law'],
  'mandatory minimum': ['mandatory minimums', 'sentencing', 'law'],
  'eminent domain': ['eminent domain', 'law'],
  'wrongful conviction': ['wrongful conviction', 'criminal justice reform', 'law'],
  'class action': ['class action reform', 'law'],
  // Economics - expanded
  'income inequality': ['income inequality', 'poverty', 'economics and public finance'],
  'inequality': ['income inequality', 'economics and public finance'],
  'debt ceiling': ['debt ceiling', 'national debt', 'economics and public finance'],
  'government shutdown': ['government shutdown', 'economics and public finance'],
  'shutdown': ['government shutdown', 'economics and public finance'],
  'gdp': ['gdp growth', 'economics and public finance'],
  'austerity': ['austerity', 'economics and public finance'],
  // Education - expanded
  'charter': ['charter schools', 'school choice', 'education'],
  'charter school': ['charter schools', 'education'],
  'voucher': ['school vouchers', 'school choice', 'education'],
  'standardized test': ['standardized testing', 'education'],
  'sat': ['standardized testing', 'education'],
  'act': ['standardized testing', 'education'],
  'sex ed': ['sex education', 'education'],
  'sex education': ['sex education', 'education'],
  'civics': ['civics education', 'education'],
  'college affordability': ['college affordability', 'higher education', 'student loans'],
  // Families - expanded
  'screen time': ['screen time', 'child safety online', 'families'],
  'social media kids': ['social media age limits', 'child safety online', 'families'],
  'fertility': ['fertility treatment', 'families'],
  'ivf': ['fertility treatment', 'families'],
  'surrogacy': ['surrogacy', 'families'],
  'grandparent rights': ['grandparent rights', 'grandparent caregivers', 'families'],
  'single parent': ['single parents', 'families'],
  // Sports - expanded
  'nil': ['nil/college athletes', 'sports and recreation'],
  'college athletes': ['nil/college athletes', 'sports and recreation'],
  'stadium': ['stadium funding', 'sports and recreation'],
  'concussion': ['youth sports safety', 'sports and recreation'],
  // Agriculture - expanded
  'food desert': ['food deserts', 'agriculture and food'],
  'food deserts': ['food deserts', 'agriculture and food'],
  'meat processing': ['meat processing', 'food safety', 'agriculture and food'],
  'ag tech': ['agricultural technology', 'agriculture and food'],
  // Native Americans - expanded
  'tribal gaming': ['tribal gaming', 'native americans'],
  'casino': ['tribal gaming', 'native americans'],
  'language preservation': ['language preservation', 'native americans'],
  // Water - expanded
  'desalination': ['desalination', 'water resources development'],
  'pfas water': ['pfas in water', 'clean drinking water', 'water resources development'],
  'stormwater': ['stormwater management', 'water resources development'],
  'levee': ['levee repair', 'flood control', 'water resources development'],
  'great lakes': ['great lakes', 'water resources development'],
  'colorado river': ['colorado river', 'water allocation', 'water resources development'],
  // Emergency - expanded
  'wildfire management': ['wildfire management', 'wildfires', 'emergency management'],
  'flood insurance': ['flood insurance', 'flood control', 'emergency management'],
  'national stockpile': ['national stockpile', 'emergency management'],
  // Trade - expanded
  'export controls': ['export controls', 'foreign trade and international finance'],
  'rare earth': ['rare earth minerals', 'foreign trade and international finance'],
  'forced labor': ['forced labor imports', 'human trafficking', 'foreign trade'],
  // International - expanded
  'who': ['who', 'global health', 'international affairs'],
  'world health': ['who', 'global health', 'international affairs'],
  'peacekeeping': ['peacekeeping', 'international affairs'],
  'climate agreement': ['climate agreements', 'international affairs'],
  'paris agreement': ['climate agreements', 'international affairs'],
  'trade war': ['trade war', 'tariffs', 'international affairs'],
  // Plain English problems people type
  "can't afford": ['cost of living', 'inflation', 'economics and public finance'],
  'too expensive': ['cost of living', 'inflation', 'economics and public finance'],
  'bills': ['utility bills', 'cost of living', 'economics and public finance'],
  'my kid': ['families', 'education', 'child care'],
  'my child': ['families', 'education', 'child care'],
  'my kids': ['families', 'education', 'child care'],
  'unsafe': ['crime and law enforcement', 'school safety', 'public health'],
  'dangerous': ['crime and law enforcement', 'school safety', 'public health'],
  'homeless people': ['homelessness', 'housing and community development'],
  'cost of living': ['cost of living', 'inflation', 'grocery prices', 'gas prices'],
  'grocery prices': ['grocery prices', 'inflation', 'cost of living'],
  'gas prices': ['gas prices', 'oil and gas', 'energy costs'],
  'utility bills': ['utility bills', 'energy costs', 'cost of living'],
  'rent prices': ['rent prices', 'rent', 'affordable housing'],
  'my rent': ['rent', 'rent prices', 'affordable housing'],
  'high rent': ['rent', 'rent prices', 'affordable housing'],
  'too much rent': ['rent', 'rent prices', 'affordable housing'],
  'afford rent': ['rent', 'rent prices', 'affordable housing', 'cost of living'],
  'afford food': ['food insecurity', 'snap/food stamps', 'grocery prices'],
  'afford gas': ['gas prices', 'energy costs', 'cost of living'],
  'afford college': ['college affordability', 'student loans', 'higher education'],
  'food prices': ['grocery prices', 'inflation', 'cost of living'],
  'electric bill': ['utility bills', 'energy costs'],
  'power bill': ['utility bills', 'energy costs'],
  'heating bill': ['utility bills', 'energy costs'],
  'water bill': ['utility bills', 'clean water', 'water infrastructure'],
  'phone bill': ['utility bills', 'internet/broadband'],
  // Current events / 2025-2026 terms
  'doge': ['doge', 'government efficiency', 'government waste', 'government operations and politics'],
  'government efficiency': ['government efficiency', 'government waste', 'government spending'],
  'government waste': ['government waste', 'government efficiency', 'government spending'],
  'elon': ['doge', 'government efficiency', 'government operations and politics'],
  'elon musk': ['doge', 'government efficiency', 'government operations and politics'],
  'mass deportation': ['deportation', 'immigration raids', 'immigration'],
  'raids': ['immigration raids', 'deportation', 'immigration'],
  'immigration raids': ['immigration raids', 'deportation', 'immigration'],
  'tiktok ban': ['tiktok ban', 'social media regulation', 'data privacy'],
  'cancel culture': ['free speech', 'censorship', 'civil rights and liberties, minority issues'],
  'crt': ['civil rights and liberties, minority issues', 'education', 'racial justice'],
  'critical race theory': ['civil rights and liberties, minority issues', 'education', 'racial justice'],
  'woke': ['dei', 'civil rights and liberties, minority issues'],
  'defund': ['police reform', 'crime and law enforcement'],
  'defund the police': ['police reform', 'crime and law enforcement'],
  'drug cartels': ['drug cartels', 'fentanyl', 'border security'],
  'cartel': ['drug cartels', 'fentanyl', 'border security'],
  'cartels': ['drug cartels', 'fentanyl', 'border security'],
  'organized crime': ['organized crime', 'crime and law enforcement'],
  // Government agency acronyms
  'cbp': ['border security', 'immigration', 'immigration detention'],
  'doj': ['criminal justice reform', 'law', 'crime and law enforcement'],
  'atf': ['gun violence', 'crime and law enforcement'],
  'cdc': ['public health', 'vaccine policy', 'health'],
  'fda': ['food safety', 'drug policy', 'prescription drug costs', 'health'],
  'hhs': ['health', 'medicare', 'medicaid'],
  'dhs': ['border security', 'immigration', 'cybersecurity'],
  'doe': ['education', 'energy', 'k-12 education'],
  'usda': ['agriculture and food', 'farming', 'food safety'],
  'epa': ['epa', 'environmental protection', 'clean air', 'clean water'],
  'hud': ['hud', 'affordable housing', 'housing and community development'],
  'va': ['veterans', 'va healthcare', 'armed forces and national security'],
  'ssa': ['social security', 'social welfare'],
  'ftc': ['consumer protection', 'antitrust', 'commerce'],
  'fcc': ['internet/broadband', 'net neutrality', 'science, technology'],
  'dea': ['drug policy', 'fentanyl', 'crime and law enforcement'],
  // Brand names people associate with issues
  'amazon': ['gig economy', 'antitrust', 'worker rights', 'tech monopolies'],
  'google': ['tech monopolies', 'data privacy', 'antitrust'],
  'facebook': ['social media regulation', 'data privacy', 'child safety online'],
  'meta': ['social media regulation', 'data privacy', 'child safety online'],
  'instagram': ['social media regulation', 'child safety online', 'youth mental health'],
  'walmart': ['minimum wage', 'worker rights', 'labor and employment'],
  'doordash': ['gig economy', 'gig worker benefits', 'worker rights'],
  'grubhub': ['gig economy', 'gig worker benefits', 'worker rights'],
  'instacart': ['gig economy', 'gig worker benefits', 'worker rights'],
  'apple': ['tech monopolies', 'data privacy', 'antitrust'],
  'twitter': ['social media regulation', 'free speech', 'data privacy'],
  'x.com': ['social media regulation', 'free speech', 'data privacy'],
  // Emotional / problem-oriented
  'bullying': ['bullying', 'school safety', 'education'],
  'bullied': ['bullying', 'school safety', 'education'],
  'cyberbullying': ['bullying', 'child safety online', 'education'],
  'overdose': ['drug overdose', 'opioids', 'fentanyl', 'health'],
  'od': ['drug overdose', 'opioids', 'fentanyl'],
  'drug overdose': ['drug overdose', 'opioids', 'fentanyl', 'health'],
  'scam': ['consumer protection', 'elder abuse', 'commerce'],
  'scammed': ['consumer protection', 'elder abuse', 'commerce'],
  'fraud': ['consumer protection', 'white collar crime', 'elder abuse'],
  'kicked out': ['eviction protections', 'homelessness', 'housing and community development'],
  'evicted': ['eviction protections', 'homelessness', 'housing and community development'],
  'laid off': ['unemployment', 'labor and employment'],
  'layoff': ['unemployment', 'labor and employment'],
  'layoffs': ['unemployment', 'labor and employment'],
  'fired': ['unemployment', 'labor and employment', 'worker rights'],
  "can't find a doctor": ['hospital access', 'rural hospitals', 'health'],
  'er wait': ['er wait times', 'hospital access', 'health'],
  'emergency room': ['er wait times', 'hospital access', 'health'],
  'health insurance': ['health insurance costs', 'aca/obamacare', 'health'],
  'insurance cost': ['health insurance costs', 'aca/obamacare', 'health'],
  'insurance costs': ['health insurance costs', 'aca/obamacare', 'health'],
  'copay': ['health insurance costs', 'prescription drug costs', 'health'],
  'deductible': ['health insurance costs', 'health'],
  'premium': ['health insurance costs', 'health'],
  'premiums': ['health insurance costs', 'aca/obamacare', 'health'],
  'uninsured': ['health insurance costs', 'aca/obamacare', 'medicaid'],
  'phone addiction': ['phone addiction', 'screen time', 'youth mental health'],
  'child hunger': ['child hunger', 'food insecurity', 'snap/food stamps', 'school meals'],
  'school board': ['school boards', 'k-12 education', 'education'],
  'school boards': ['school boards', 'k-12 education', 'education'],
  'migrant': ['migrant workers', 'immigration', 'asylum'],
  'migrant workers': ['migrant workers', 'agricultural workers', 'immigration'],
  'migrants': ['migrant workers', 'immigration', 'asylum'],
  // Common alternate spellings/forms
  'healthcare': ['health', 'aca/obamacare', 'health insurance costs'],
  'obamacare': ['aca/obamacare', 'health insurance costs', 'health'],
  'govt': ['government spending', 'government operations and politics', 'federal agencies'],
  'rep': ['congressional reform', 'congress'],
  'reps': ['congressional reform', 'congress'],
  'e verify': ['e-verify', 'immigration'],
  'everify': ['e-verify', 'immigration'],
  'pre k': ['pre-k', 'early childhood education'],
  'prek': ['pre-k', 'early childhood education'],
  // Additional everyday terms people might search
  'paycheck': ['minimum wage', 'wage growth', 'labor and employment'],
  'broke': ['cost of living', 'poverty', 'economics and public finance'],
  'struggling': ['cost of living', 'poverty', 'economics and public finance'],
  'afford': ['cost of living', 'inflation', 'economics and public finance'],
  'safety': ['crime and law enforcement', 'school safety', 'public health'],
  'stealing': ['retail theft', 'crime and law enforcement'],
  'theft': ['retail theft', 'crime and law enforcement'],
  'robbery': ['crime and law enforcement'],
  'murder': ['crime and law enforcement', 'gun violence'],
  'drunk driving': ['crime and law enforcement', 'highway safety'],
  'dui': ['crime and law enforcement'],
  'speeding': ['highway safety', 'pedestrian safety', 'transportation'],
  'pothole': ['roads', 'infrastructure'],
  'commute': ['public transit', 'roads', 'transportation'],
  'daycamp': ['child care', 'families'],
  'babysitter': ['child care', 'families'],
  'nanny': ['child care', 'families'],
  'student': ['student loans', 'higher education', 'education'],
  'tutor': ['k-12 education', 'education'],
  'textbook': ['higher education', 'college affordability', 'education'],
  'diploma': ['k-12 education', 'education'],
  'ged': ['k-12 education', 'education'],
};

// Pre-built flat list for search
let cachedOptions: IssueOption[] | null = null;

export function getAllIssueOptions(): IssueOption[] {
  if (cachedOptions) return cachedOptions;

  cachedOptions = [];
  for (const [category, subtopics] of Object.entries(POLICY_AREAS)) {
    for (const label of subtopics) {
      cachedOptions.push({ label, category });
    }
  }
  return cachedOptions;
}

/** Strip hyphens and collapse whitespace for fuzzy matching */
function normalize(text: string): string {
  return text.replace(/-/g, ' ').replace(/\s+/g, ' ');
}

export function searchIssues(query: string): IssueOption[] {
  const q = query.trim().toLowerCase();
  if (!q) return getAllIssueOptions();

  const qNorm = normalize(q);

  // Expand query with keyword aliases
  const expandedTerms = new Set<string>();
  // Track exact alias matches (full query = alias key) for boosted scoring
  const exactAliasTerms = new Set<string>();
  // Add original terms
  const originalTerms = qNorm.split(/\s+/);
  for (const term of originalTerms) {
    expandedTerms.add(term);
  }
  // Check for multi-word aliases (e.g., "food stamps", "social security")
  // Match against both the raw query and the normalized query
  for (const [alias, expansions] of Object.entries(KEYWORD_ALIASES)) {
    if (qNorm.includes(alias) || q.includes(alias)) {
      const isExactMatch = qNorm === alias || q === alias;
      for (const expansion of expansions) {
        expandedTerms.add(expansion);
        if (isExactMatch) exactAliasTerms.add(expansion);
      }
    }
  }

  const allOptions = getAllIssueOptions();

  // Score each option: higher score = better match
  const scored = allOptions.map((option) => {
    const raw = `${option.label} ${option.category}`.toLowerCase();
    const haystack = normalize(raw);
    let score = 0;

    // Direct match on original terms (highest weight)
    for (const term of originalTerms) {
      if (haystack.includes(term)) score += 10;
    }

    // Expanded term matches (lower weight, unless from exact alias match)
    for (const term of expandedTerms) {
      if (originalTerms.includes(term)) continue; // already counted
      if (haystack.includes(term)) {
        score += exactAliasTerms.has(term) ? 15 : 5;
      }
    }

    return { option, score };
  });

  // Filter to options with any match, sort by score descending
  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((s) => s.option);
}
