/**
 * The curated issue picker topics. Categories are Library of Congress
 * policy areas — the same values the Senate/House CWC APIs accept as
 * <LibraryOfCongressTopic>, so a picked issue is CWC-ready as-is.
 *
 * Every entry here MUST route through a hand-audited jurisdiction rule
 * (never the default fallback) — enforced by issue-jurisdiction tests.
 */

export const POPULAR_TOPICS: { label: string; category: string; subtopics: { label: string; category: string }[] }[] = [
  {
    label: 'Healthcare',
    category: 'Health',
    subtopics: [
      { label: 'Medicare', category: 'Health' },
      { label: 'Medicaid', category: 'Health' },
      { label: 'Prescription Drug Costs', category: 'Health' },
      { label: 'Mental Health', category: 'Health' },
      { label: 'Reproductive Health', category: 'Health' },
      { label: 'ACA / Obamacare', category: 'Health' },
      { label: 'Infant/Early Childhood Mental Health', category: 'Health' },
      { label: 'Maternal Health', category: 'Health' },
      { label: 'Dental Care', category: 'Health' },
      { label: 'Vaccine Policy', category: 'Health' },
      { label: 'Insulin Pricing', category: 'Health' },
      { label: 'Rural Hospitals', category: 'Health' },
      { label: 'Medical Debt', category: 'Health' },
      { label: 'Gender-Affirming Care', category: 'Health' },
    ],
  },
  {
    label: 'Immigration',
    category: 'Immigration',
    subtopics: [
      { label: 'Border Security', category: 'Immigration' },
      { label: 'DACA (Dreamers)', category: 'Immigration' },
      { label: 'Visas', category: 'Immigration' },
      { label: 'Asylum', category: 'Immigration' },
      { label: 'Refugee Policy', category: 'Immigration' },
      { label: 'Deportation', category: 'Immigration' },
      { label: 'Legal Immigration', category: 'Immigration' },
      { label: 'TPS (Temporary Protected Status)', category: 'Immigration' },
      { label: 'E-Verify (Work Authorization)', category: 'Immigration' },
      { label: 'Family Separation', category: 'Immigration' },
      { label: 'Sanctuary Cities', category: 'Immigration' },
    ],
  },
  {
    label: 'Economy',
    category: 'Economics and Public Finance',
    subtopics: [
      { label: 'Inflation', category: 'Economics and Public Finance' },
      { label: 'Cost of Living', category: 'Economics and Public Finance' },
      { label: 'Federal Budget', category: 'Economics and Public Finance' },
      { label: 'National Debt', category: 'Economics and Public Finance' },
      { label: 'Wage Growth', category: 'Economics and Public Finance' },
      { label: 'Recession', category: 'Economics and Public Finance' },
      { label: 'Debt Ceiling', category: 'Economics and Public Finance' },
      { label: 'Income Inequality', category: 'Economics and Public Finance' },
      { label: 'Government Shutdown', category: 'Economics and Public Finance' },
    ],
  },
  {
    label: 'Education',
    category: 'Education',
    subtopics: [
      { label: 'K-12 Education', category: 'Education' },
      { label: 'Student Loans', category: 'Education' },
      { label: 'Higher Education', category: 'Education' },
      { label: 'School Choice', category: 'Education' },
      { label: 'School Safety', category: 'Education' },
      { label: 'Teacher Pay', category: 'Education' },
      { label: 'Early Childhood Education', category: 'Education' },
      { label: 'Book Bans', category: 'Education' },
      { label: 'Charter Schools', category: 'Education' },
      { label: 'College Affordability', category: 'Education' },
      { label: 'Student Debt Forgiveness', category: 'Education' },
      { label: 'Civics Education', category: 'Education' },
    ],
  },
  {
    label: 'Crime & Justice',
    category: 'Crime and Law Enforcement',
    subtopics: [
      { label: 'Gun Violence', category: 'Crime and Law Enforcement' },
      { label: 'Criminal Justice Reform', category: 'Crime and Law Enforcement' },
      { label: 'Police Reform', category: 'Crime and Law Enforcement' },
      { label: 'Drug Policy', category: 'Crime and Law Enforcement' },
      { label: 'Fentanyl', category: 'Crime and Law Enforcement' },
      { label: 'Domestic Violence', category: 'Crime and Law Enforcement' },
      { label: 'Human Trafficking', category: 'Crime and Law Enforcement' },
      { label: 'Juvenile Justice', category: 'Crime and Law Enforcement' },
      { label: 'Bail Reform', category: 'Crime and Law Enforcement' },
      { label: 'Death Penalty', category: 'Crime and Law Enforcement' },
      { label: 'Retail Theft', category: 'Crime and Law Enforcement' },
      { label: 'School Shootings', category: 'Crime and Law Enforcement' },
      { label: 'Elder Abuse', category: 'Crime and Law Enforcement' },
      { label: 'Body Cameras', category: 'Crime and Law Enforcement' },
    ],
  },
  {
    label: 'Climate & Energy',
    category: 'Environmental Protection',
    subtopics: [
      { label: 'Climate Change', category: 'Environmental Protection' },
      { label: 'Renewable Energy', category: 'Energy' },
      { label: 'Oil and Gas', category: 'Energy' },
      { label: 'Nuclear Energy', category: 'Energy' },
      { label: 'Electric Vehicles', category: 'Energy' },
      { label: 'Clean Air', category: 'Environmental Protection' },
      { label: 'Clean Water', category: 'Environmental Protection' },
      { label: 'Wildfires', category: 'Environmental Protection' },
      { label: 'Carbon Capture', category: 'Environmental Protection' },
      { label: 'Offshore Wind', category: 'Energy' },
      { label: 'Methane', category: 'Environmental Protection' },
      { label: 'Energy Storage', category: 'Energy' },
    ],
  },
  {
    label: 'Housing',
    category: 'Housing and Community Development',
    subtopics: [
      { label: 'Affordable Housing', category: 'Housing and Community Development' },
      { label: 'Rent', category: 'Housing and Community Development' },
      { label: 'Homelessness', category: 'Housing and Community Development' },
      { label: 'Mortgage Rates', category: 'Housing and Community Development' },
      { label: 'Zoning Reform', category: 'Housing and Community Development' },
      { label: 'Public Housing', category: 'Housing and Community Development' },
      { label: 'Rent Control', category: 'Housing and Community Development' },
      { label: 'First-Time Homebuyers', category: 'Housing and Community Development' },
      { label: 'Eviction Protections', category: 'Housing and Community Development' },
      { label: 'Gentrification', category: 'Housing and Community Development' },
    ],
  },
  {
    label: 'Taxes',
    category: 'Taxation',
    subtopics: [
      { label: 'Income Tax', category: 'Taxation' },
      { label: 'Corporate Tax', category: 'Taxation' },
      { label: 'Tax Reform', category: 'Taxation' },
      { label: 'Wealth Tax', category: 'Taxation' },
      { label: 'Capital Gains Tax', category: 'Taxation' },
      { label: 'Tariffs', category: 'Foreign Trade and International Finance' },
      { label: 'SALT Deduction (State & Local Tax)', category: 'Taxation' },
      { label: 'Property Tax', category: 'Taxation' },
      { label: 'Carbon Tax', category: 'Taxation' },
    ],
  },
  {
    label: 'Social Security & Safety Net',
    category: 'Social Welfare',
    subtopics: [
      { label: 'Social Security', category: 'Social Welfare' },
      { label: 'Disability Benefits', category: 'Social Welfare' },
      { label: 'Safety Net Programs', category: 'Social Welfare' },
      { label: 'Food Assistance', category: 'Social Welfare' },
      { label: 'Senior Care', category: 'Social Welfare' },
      { label: 'Universal Basic Income', category: 'Social Welfare' },
      { label: 'WIC (Women, Infants & Children)', category: 'Social Welfare' },
      { label: 'Section 8 / Housing Vouchers', category: 'Social Welfare' },
      { label: 'SSI (Supplemental Security Income)', category: 'Social Welfare' },
    ],
  },
  {
    label: 'Veterans & Military',
    category: 'Armed Forces and National Security',
    subtopics: [
      { label: 'Veterans', category: 'Armed Forces and National Security' },
      { label: 'VA Healthcare', category: 'Armed Forces and National Security' },
      { label: 'PTSD', category: 'Armed Forces and National Security' },
      { label: 'Military Funding', category: 'Armed Forces and National Security' },
      { label: 'Defense Spending', category: 'Armed Forces and National Security' },
      { label: 'Military Families', category: 'Armed Forces and National Security' },
      { label: 'Cybersecurity', category: 'Armed Forces and National Security' },
      { label: 'Veteran Suicide', category: 'Armed Forces and National Security' },
      { label: 'Military Sexual Assault', category: 'Armed Forces and National Security' },
      { label: 'Defense Contracts', category: 'Armed Forces and National Security' },
    ],
  },
  {
    label: 'Civil Rights',
    category: 'Civil Rights and Liberties, Minority Issues',
    subtopics: [
      { label: 'Voting Rights', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Discrimination', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'LGBTQ+ Rights', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Free Speech', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Racial Justice', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Police Accountability', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'DEI (Diversity, Equity & Inclusion)', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Equal Pay', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Voter Suppression', category: 'Civil Rights and Liberties, Minority Issues' },
      { label: 'Religious Exemptions', category: 'Civil Rights and Liberties, Minority Issues' },
    ],
  },
  {
    label: 'Jobs & Workers',
    category: 'Labor and Employment',
    subtopics: [
      { label: 'Minimum Wage', category: 'Labor and Employment' },
      { label: 'Worker Rights', category: 'Labor and Employment' },
      { label: 'Unions', category: 'Labor and Employment' },
      { label: 'Paid Sick Leave', category: 'Labor and Employment' },
      { label: 'Overtime Pay', category: 'Labor and Employment' },
      { label: 'Non-Compete Agreements', category: 'Labor and Employment' },
      { label: 'Gig Worker Benefits', category: 'Labor and Employment' },
      { label: 'Tipped Minimum Wage', category: 'Labor and Employment' },
      { label: 'Workplace Harassment', category: 'Labor and Employment' },
    ],
  },
  {
    label: 'Families',
    category: 'Families',
    subtopics: [
      { label: 'Child Care', category: 'Families' },
      { label: 'Paid Family Leave', category: 'Families' },
      { label: 'Child Tax Credit', category: 'Families' },
      { label: 'Child Safety Online', category: 'Families' },
      { label: 'Foster Care', category: 'Families' },
      { label: 'Youth Mental Health', category: 'Families' },
      { label: 'Social Media Age Limits', category: 'Families' },
      { label: 'Screen Time', category: 'Families' },
      { label: 'Fertility Treatment', category: 'Families' },
    ],
  },
  {
    label: 'Technology',
    category: 'Science, Technology, Communications',
    subtopics: [
      { label: 'AI', category: 'Science, Technology, Communications' },
      { label: 'Data Privacy', category: 'Science, Technology, Communications' },
      { label: 'Social Media Regulation', category: 'Science, Technology, Communications' },
      { label: 'Cybersecurity', category: 'Science, Technology, Communications' },
      { label: 'Net Neutrality (Open Internet)', category: 'Science, Technology, Communications' },
      { label: 'Deepfakes', category: 'Science, Technology, Communications' },
      { label: 'Semiconductors / CHIPS Act', category: 'Science, Technology, Communications' },
      { label: 'Age Verification', category: 'Science, Technology, Communications' },
      { label: 'Autonomous Vehicles', category: 'Science, Technology, Communications' },
    ],
  },
  {
    label: 'Foreign Policy',
    category: 'International Affairs',
    subtopics: [
      { label: 'Ukraine', category: 'International Affairs' },
      { label: 'Israel/Palestine', category: 'International Affairs' },
      { label: 'Iran', category: 'International Affairs' },
      { label: 'China', category: 'International Affairs' },
      { label: 'Russia', category: 'International Affairs' },
      { label: 'NATO', category: 'International Affairs' },
      { label: 'Foreign Aid', category: 'International Affairs' },
      { label: 'Tariffs', category: 'Foreign Trade and International Finance' },
      { label: 'Sanctions Enforcement', category: 'International Affairs' },
      { label: 'Trade War', category: 'International Affairs' },
      { label: 'Taiwan', category: 'International Affairs' },
      { label: 'Venezuela', category: 'International Affairs' },
    ],
  },
];
