/**
 * Participant-facing copy for the campaign participation flow, in the
 * campaign's language. English is the source; Spanish follows the same
 * flat, declarative register. Add a key here and to both blocks; the type
 * keeps the two in step.
 */
export type CampaignLanguage = 'en' | 'es';

const en = {
  // Stance step
  positionTitle: 'What’s your position?',
  positionHelp: 'Both sides are laid out above. Your message will carry your position. My Democracy does not take a side.',
  supportLabel: 'I support this',
  supportHelp: 'Your message will express clear support and ask your officials to support it too.',
  opposeLabel: 'I oppose this',
  opposeHelp: 'Your message will express clear opposition and ask your officials to oppose it.',
  stanceSupport: 'Support',
  stanceOppose: 'Oppose',
  stanceUndecided: 'Still deciding',
  yourPosition: 'Your position:',
  change: 'Change',

  // Compose step
  followUpTitle: 'A couple quick questions',
  writing: 'Writing your message…',
  continue: 'Continue',
  whyLabel: 'Why does this matter to you?',
  whyOptional: '(optional, but it makes your message land)',
  whyPlaceholder: 'How does this affect you, your family, your community? A sentence or two is plenty.',
  oneMoment: 'One moment…',
  draftMyMessage: 'Draft my message',
  reviewBeforeAnything: 'You will see and edit the message before anything else happens. No address needed yet.',
  yourMessage: 'Your message',
  yourMessageHint: '(edit anything, these are your words)',
  greetingAdded: 'We add the greeting and each official’s name automatically. Your words above are never changed.',
  looksGoodNext: 'Looks good. Next: your address',
  redrafting: 'Redrafting…',
  redraft: 'Redraft',
  draftFailed: 'We could not draft your message. You can write it yourself below, or try again.',

  // Guided chat (compose step)
  guideGreeting: (headline: string) => `Hi. I’m here to help you say why this matters to you, so your message carries your own experience. There is no rush, and you can skip anything.\n\nTo start: what is your connection to "${headline}", or what has happened that makes you care about it?`,
  chatPlaceholder: 'Share as much or as little as you like…',
  send: 'Send',
  ratherNotSay: 'Rather not say',
  ratherNotSayInput: 'I’d rather not say.',
  guideReadyHint: 'You will see and edit the message before anything else happens.',
  guideMoreHint: 'A little more first. The message is built only from what you write here.',
  writeItMyself: 'Skip the questions and write it myself',
  useTheGuide: 'Answer a few questions instead',
  skip: 'Skip',
  followUpHelp: 'Your answers make your letter specific. Skip anything.',

  // Form step
  prefilled: 'Your info has been filled from your account. Edit if needed.',
  title: 'Title',
  choose: 'Choose',
  yourName: 'Your Name',
  yourNamePlaceholder: 'Your full name',
  email: 'Email',
  emailRequiredNote: 'Congressional offices require an email address to accept and reply to your message. Never shared or sold.',
  emailFollowUpNote: (org: string) => `${org} will email you when this bill moves to its next step, so you can act again when it counts. Unsubscribe anytime.`,
  organizerFallback: 'The campaign organizer',
  streetAddress: 'Street Address',
  streetPlaceholder: '123 Main St',
  city: 'City',
  state: 'State',
  selectState: 'Select state',
  zip: 'ZIP Code',
  approvedGoesToEach: 'Your approved message goes to each official with their own greeting and ask. You’ll review everything before sending.',
  findMyOfficials: 'Find My Officials',
  addressUse: 'Your address is used to find your officials and, for congressional offices, is sent with your message so they can confirm you are a constituent. See our',
  privacyPolicy: 'Privacy Policy',

  // Loading
  findingOfficials: 'Finding your officials...',
  generatingMessages: 'Generating personalized messages',

  // Review step
  messagesReady: (n: number) => `${n} Message${n !== 1 ? 's' : ''} Ready`,
  sendEachBelow: 'Send each message using the options below',
  seeTalkingPoints: 'See the talking points your messages will include',
  everythingElseYourVoice: 'Everything else is written for your voice. Edit anything before you send.',
  aiUnavailable: 'Our AI writer isn’t available right now, so we’ve started each message for you.',
  makeItYourOwn: 'Please make it your own before sending. Personal words carry the most weight with officials.',
  done: 'Done',

  // Send card
  stateBadge: 'State',
  sentToCongress: 'Sent to Congress',
  sending: 'Sending',
  sendToCongress: 'Send to Congress',
  sendEmail: 'Send Email',
  openContactForm: 'Open Contact Form',
  visitWebsite: 'Visit Website',
  call: 'Call',
  noContactMethod: 'No contact method available',
  copied: 'Copied!',
  copyMessage: 'Copy Message',
  viewEditMessage: 'View & edit message',
  subject: 'Subject',
  message: 'Message',
  cwcIdle: 'Goes straight to the office through Communicating with Congress, the message system run by the House and Senate. No email app needed. Your name and address travel in separate fields, so no signature is needed in the text.',
  cwcSending: 'Handing your message to the congressional delivery system.',
  cwcSent: 'Received by the congressional delivery system. Delivery usually completes within minutes and pauses overnight during House and Senate maintenance windows.',
  webformIdle: 'This office does not use the congressional delivery system yet, so My Democracy files your message in the office’s own contact form for you. No email app needed. Your name and address go in the form’s own fields.',
  webformSending: 'Handing your message to the delivery queue.',
  webformSent: 'Received. My Democracy will file it in the office’s contact form within about an hour.',

  // Done step
  sent: 'Sent',
  nothingSentYet: 'Nothing sent yet',
  inTheCount: 'Offices tally constituent messages by issue. Yours is now in the count.',
  sendWhenReady: 'You can go back and send your message whenever you are ready.',
  readersSoFar: 'How My Democracy readers have landed so far',
  beFirst: 'Be one of the first to weigh in. Results appear once more readers have.',
  youreWith: (pct: number) => `You’re with the ${pct}%.`,
  yourPositionSuffix: ' (your position)',
};

export type ParticipateCopy = typeof en;

const es: ParticipateCopy = {
  positionTitle: '¿Cuál es su posición?',
  positionHelp: 'Arriba se presentan los dos lados. Su mensaje llevará su posición. My Democracy no toma partido.',
  supportLabel: 'Apoyo esto',
  supportHelp: 'Su mensaje expresará un apoyo claro y pedirá a sus funcionarios que también lo apoyen.',
  opposeLabel: 'Me opongo a esto',
  opposeHelp: 'Su mensaje expresará una oposición clara y pedirá a sus funcionarios que se opongan.',
  stanceSupport: 'A favor',
  stanceOppose: 'En contra',
  stanceUndecided: 'Sin decidir',
  yourPosition: 'Su posición:',
  change: 'Cambiar',

  followUpTitle: 'Un par de preguntas rápidas',
  writing: 'Escribiendo su mensaje…',
  continue: 'Continuar',
  whyLabel: '¿Por qué le importa este tema?',
  whyOptional: '(opcional, pero hace que su mensaje tenga más peso)',
  whyPlaceholder: '¿Cómo le afecta a usted, a su familia o a su comunidad? Con una o dos oraciones basta.',
  oneMoment: 'Un momento…',
  draftMyMessage: 'Redactar mi mensaje',
  reviewBeforeAnything: 'Verá y podrá editar el mensaje antes de cualquier otra cosa. Todavía no necesita dar su dirección.',
  yourMessage: 'Su mensaje',
  yourMessageHint: '(edite lo que quiera, estas son sus palabras)',
  greetingAdded: 'Nosotros agregamos el saludo y el nombre de cada funcionario. Sus palabras nunca se cambian.',
  looksGoodNext: 'Se ve bien. Siguiente: su dirección',
  redrafting: 'Redactando de nuevo…',
  redraft: 'Redactar de nuevo',
  draftFailed: 'No pudimos redactar su mensaje. Puede escribirlo usted mismo abajo o intentarlo de nuevo.',

  guideGreeting: (headline: string) => `Hola. Estoy aquí para ayudarle a decir por qué este tema le importa, para que su mensaje lleve su propia experiencia. No hay prisa, y puede saltarse lo que quiera.\n\nPara empezar: ¿cuál es su relación con "${headline}", o qué ha pasado que le hace importarle?`,
  chatPlaceholder: 'Comparta tanto o tan poco como quiera…',
  send: 'Enviar',
  ratherNotSay: 'Prefiero no decirlo',
  ratherNotSayInput: 'Prefiero no decirlo.',
  guideReadyHint: 'Verá y podrá editar el mensaje antes de cualquier otra cosa.',
  guideMoreHint: 'Un poco más primero. El mensaje se construye solo con lo que usted escribe aquí.',
  writeItMyself: 'Saltar las preguntas y escribirlo yo mismo',
  useTheGuide: 'Responder unas preguntas en su lugar',
  skip: 'Saltar',
  followUpHelp: 'Sus respuestas hacen que su carta sea específica. Sáltese lo que quiera.',

  prefilled: 'Sus datos se completaron desde su cuenta. Edítelos si hace falta.',
  title: 'Título',
  choose: 'Elegir',
  yourName: 'Su nombre',
  yourNamePlaceholder: 'Su nombre completo',
  email: 'Correo electrónico',
  emailRequiredNote: 'Las oficinas del Congreso requieren un correo electrónico para aceptar y responder su mensaje. Nunca se comparte ni se vende.',
  emailFollowUpNote: (org: string) => `${org} le enviará un correo cuando este proyecto de ley avance a su siguiente paso, para que pueda actuar de nuevo cuando cuente. Puede darse de baja cuando quiera.`,
  organizerFallback: 'La organización de la campaña',
  streetAddress: 'Dirección',
  streetPlaceholder: 'Calle Principal 123',
  city: 'Ciudad',
  state: 'Estado',
  selectState: 'Seleccione el estado',
  zip: 'Código postal',
  approvedGoesToEach: 'Su mensaje aprobado se envía a cada funcionario con su propio saludo y petición. Revisará todo antes de enviarlo.',
  findMyOfficials: 'Buscar mis funcionarios',
  addressUse: 'Su dirección se usa para encontrar a sus funcionarios y, en el caso de las oficinas del Congreso, se envía con su mensaje para que confirmen que usted es un constituyente. Vea nuestra',
  privacyPolicy: 'Política de privacidad',

  findingOfficials: 'Buscando a sus funcionarios...',
  generatingMessages: 'Preparando mensajes personalizados',

  messagesReady: (n: number) => `${n} mensaje${n !== 1 ? 's' : ''} listo${n !== 1 ? 's' : ''}`,
  sendEachBelow: 'Envíe cada mensaje con las opciones de abajo',
  seeTalkingPoints: 'Ver los puntos clave que incluirán sus mensajes',
  everythingElseYourVoice: 'Todo lo demás está escrito con su voz. Edite lo que quiera antes de enviar.',
  aiUnavailable: 'Nuestro redactor automático no está disponible ahora, así que iniciamos cada mensaje por usted.',
  makeItYourOwn: 'Hágalo suyo antes de enviarlo. Las palabras personales son las que más pesan para los funcionarios.',
  done: 'Listo',

  stateBadge: 'Estatal',
  sentToCongress: 'Enviado al Congreso',
  sending: 'Enviando',
  sendToCongress: 'Enviar al Congreso',
  sendEmail: 'Enviar correo',
  openContactForm: 'Abrir formulario de contacto',
  visitWebsite: 'Visitar sitio web',
  call: 'Llamar al',
  noContactMethod: 'No hay un método de contacto disponible',
  copied: '¡Copiado!',
  copyMessage: 'Copiar mensaje',
  viewEditMessage: 'Ver y editar mensaje',
  subject: 'Asunto',
  message: 'Mensaje',
  cwcIdle: 'Va directo a la oficina a través de Communicating with Congress, el sistema de mensajes de la Cámara y el Senado. No necesita una aplicación de correo. Su nombre y dirección viajan en campos separados, así que el texto no necesita firma.',
  cwcSending: 'Entregando su mensaje al sistema de envío del Congreso.',
  cwcSent: 'Recibido por el sistema de envío del Congreso. La entrega suele completarse en minutos y se pausa de noche durante el mantenimiento de la Cámara y el Senado.',
  webformIdle: 'Esta oficina todavía no usa el sistema de envío del Congreso, así que My Democracy registra su mensaje en el formulario de contacto de la oficina por usted. No necesita una aplicación de correo. Su nombre y dirección van en los campos del formulario.',
  webformSending: 'Entregando su mensaje a la cola de envío.',
  webformSent: 'Recibido. My Democracy lo registrará en el formulario de contacto de la oficina en aproximadamente una hora.',

  sent: 'Enviado',
  nothingSentYet: 'Todavía no se ha enviado nada',
  inTheCount: 'Las oficinas cuentan los mensajes de constituyentes por tema. El suyo ya está en la cuenta.',
  sendWhenReady: 'Puede volver y enviar su mensaje cuando esté listo.',
  readersSoFar: 'Cómo se han posicionado los lectores de My Democracy hasta ahora',
  beFirst: 'Sea de los primeros en opinar. Los resultados aparecen cuando más lectores hayan participado.',
  youreWith: (pct: number) => `Usted está con el ${pct}%.`,
  yourPositionSuffix: ' (su posición)',
};

export function participateCopy(language: string | null | undefined): ParticipateCopy {
  return language === 'es' ? es : en;
}
