/**
 * Storyteller-facing copy for the storytelling campaign flow, in the
 * campaign's language. English is the source. The consent step is the
 * legally meaningful part: each Spanish line says exactly what its English
 * line says, no more and no less.
 */
import type { AttributionLevel } from '@/lib/types';

const en = {
  // Intro
  howItWorks: 'How it works',
  step1: 'We ask a few gentle questions to help you put your experience into words, at your pace.',
  step2: 'We write a draft from your answers only. You review and edit every word.',
  step3: 'You choose how you are credited and which uses you allow.',
  step4: 'You press Submit. The story goes to the campaign’s dashboard. Nothing is shared before that.',
  nothingSharedUntil: 'Nothing is shared until you review the draft, choose how you are credited, and press Submit.',
  startMyStory: 'Start my story',

  // Guide greeting
  greetingLead: 'Hi. I’m here to help you put your experience into words. There is no rush, and you can skip anything.',
  toStart: 'To start:',
  toStartDefault: (headline: string) => `what’s your experience with ${headline}, or what happened?`,

  // Interview
  ratherNotSayInput: 'I’d rather not say.',
  ratherNotSay: 'Rather not say',
  sharePlaceholder: 'Share as much or as little as you like…',
  send: 'Send',
  turnIntoStory: 'Turn this into my story',
  canComposeHint: 'You can edit the draft and choose how you are credited before anything is submitted.',
  needMoreHint: 'A little more detail first. The draft is built only from what you write here.',
  connectError: 'Sorry, we could not connect just now. Please try again.',
  somethingWrong: 'Something went wrong',
  composeFailed: 'Could not compose your story',
  editFailed: 'Could not make that edit',
  prepareFailed: 'Could not prepare your story',
  submitFailed: 'Could not submit your story',
  withdrawFailed: 'Could not withdraw the story',
  withdrawn: 'Your story was withdrawn. The campaign can no longer see it.',

  // Review
  titleLabel: 'Title',
  optional: '(optional)',
  yourStory: 'Your story',
  draftNote: 'We wrote this draft from your answers and kept your words where we could. Nothing here comes from anywhere else. Change anything you want.',
  wantChange: 'Want a change made for you?',
  describeEdit: 'Describe the edit and it happens, using only what you shared. Nothing gets made up.',
  editPlaceholder: 'e.g. "Make it shorter" or "Start with the part about my son"',
  makeEdit: 'Make the edit',
  backToQuestions: 'Back to the questions',
  continue: 'Continue',

  // Consent
  consentTitle: 'How you are credited, and what you allow',
  chooseCredit: 'Choose how you are credited',
  attribution: {
    named: { label: 'Use my full name', help: 'Your story is attributed to your name.' },
    first_name_only: { label: 'First name only', help: 'We remove your last name before the story is sent.' },
    anonymous: { label: 'Keep me anonymous', help: 'We remove names, places, and other identifying details before the campaign sees it. You check the result first.' },
  } as Record<AttributionLevel, { label: string; help: string }>,
  yourFirstName: 'Your first name',
  yourName: 'Your name',
  firstNamePlaceholder: 'First name',
  fullNamePlaceholder: 'Full name',
  keepFirstOnly: 'If you enter a full name, we keep only your first name.',
  yourAddress: 'Your address',
  addressOnce: 'We use your street address once, to confirm you are a constituent. The street is never shared and never stored. Below you choose whether the campaign sees your city, state, and representatives.',
  shareLocationLabel: 'Share my city, state, and the officials who represent me with this campaign',
  campaignWillSeeA: 'The campaign will see',
  yourCityState: 'your city and state',
  campaignWillSeeB: 'and the names of your elected officials, so it can bring your story to the people who represent you.',
  withoutLocation: 'The campaign will see your story without a location.',
  howMayUse: 'How this campaign may use your story',
  howMayUseQ: 'How may the campaign use your story?',
  checkEach: 'Uncheck any way you are not comfortable with. The campaign may only use your story in the ways left checked. You can uncheck all of them: the campaign can then read it but not use it elsewhere.',
  usage: {
    shared_with_legislators: { label: 'Shared with elected officials', description: 'Sent to or shown to lawmakers and their staff to support the cause.' },
    published_web_social: { label: 'Published on web or social media', description: 'Posted on the organization’s website or social channels.' },
    included_in_reports: { label: 'Quoted in reports & materials', description: 'Used in reports, presentations, or printed materials.' },
    shared_with_media: { label: 'Shared with the press', description: 'Given to journalists or news outlets covering the issue.' },
    used_in_campaign_messaging: { label: 'Used in campaign messaging', description: 'Included in the organization’s emails, fundraising, or advocacy campaigns.' },
    contact_me_followup: { label: 'They may contact me about it', description: 'The organization can reach out to you about your story.' },
  } as Record<string, { label: string; description: string }>,
  contactEmail: 'Contact email',
  emailPlaceholder: 'you@example.com',
  sharedOnlyIfTyped: 'Shared with this campaign only, and only if you type it here.',
  shareWith: 'Share my story with',
  throughDashboard: 'through their dashboard.',
  anonSavedNote: ' No name, contact, or location is saved with it.',
  truthful: 'This is my own experience and it is truthful to the best of my knowledge.',
  adult: 'I am 18 or older, or a parent or guardian sharing my family’s experience.',
  laterSignedIn: 'You can edit or withdraw your story later from your dashboard. Anything the campaign already used before you change it may not be fully recallable.',
  laterAnon: 'After you submit you will get a withdraw link on the next screen. Keep it: without an account it is the only way to remove the story later. Anything the campaign already used before then may not be fully recallable.',
  back: 'Back',
  checkAnonVersion: 'Check the anonymous version',
  submitStory: 'Submit story',
  vChooseCredit: 'Please choose how you would like to be credited.',
  vConfirmShare: (headline: string) => `Please confirm you want to share your story with ${headline}.`,
  vConfirmTruthful: 'Please confirm this is your own true experience.',
  vConfirmAdult: 'Please confirm you are 18 or older, or a parent or guardian sharing a family experience.',
  vEnterName: 'Please enter the name you would like used, or choose to stay anonymous.',
  vEnterAddress: 'Please enter your address. The street is used only to confirm you are a constituent and is never stored.',

  // Preview (anonymous)
  previewTitle: 'This is what the campaign will receive',
  previewNote: 'We removed names, places, and other details that could identify you. Read it once more. Nothing has been saved yet.',
  checkDetails: 'Please check these details yourself:',
  anonAria: 'Anonymous version of your story',
  submitThisVersion: 'Submit this version',

  // Done
  thankYou: 'Thank you for sharing',
  storyWithdrawn: 'Story withdrawn',
  canReadNow: 'The campaign can now read your story in its dashboard.',
  canNoLonger: 'The campaign can no longer see it.',
  unresolved: 'Details we could not fully resolve:',
  copied: 'Copied',
  copyMyStory: 'Copy my story',
  editFromDashboardA: 'You can edit or withdraw this story from your',
  dashboard: 'dashboard',
  changedMind: 'Changed your mind? You can',
  withdrawNow: 'withdraw it now',
  keepLink: '. To withdraw later, keep this link:',
  shareText: (headline: string) => `I shared my story with "${headline}". You can share yours here:`,
  shareTitle: (headline: string) => `Share your story: ${headline}`,
  sharePrompt: 'Know someone with a story? Send them the campaign link.',
  sharesLinkOnly: 'This shares a link to the campaign, never your story.',
};

export type StorytellerCopy = typeof en;

const es: StorytellerCopy = {
  howItWorks: 'Cómo funciona',
  step1: 'Le hacemos algunas preguntas sencillas para ayudarle a poner su experiencia en palabras, a su ritmo.',
  step2: 'Escribimos un borrador solo con sus respuestas. Usted revisa y edita cada palabra.',
  step3: 'Usted elige cómo se le acredita y qué usos permite.',
  step4: 'Usted pulsa Enviar. La historia va al panel de la campaña. Nada se comparte antes de eso.',
  nothingSharedUntil: 'Nada se comparte hasta que revise el borrador, elija cómo se le acredita y pulse Enviar.',
  startMyStory: 'Empezar mi historia',

  greetingLead: 'Hola. Estoy aquí para ayudarle a poner su experiencia en palabras. No hay prisa, y puede saltarse lo que quiera.',
  toStart: 'Para empezar:',
  toStartDefault: (headline: string) => `¿cuál es su experiencia con ${headline}, o qué pasó?`,

  ratherNotSayInput: 'Prefiero no decirlo.',
  ratherNotSay: 'Prefiero no decirlo',
  sharePlaceholder: 'Comparta tanto o tan poco como quiera…',
  send: 'Enviar',
  turnIntoStory: 'Convertir esto en mi historia',
  canComposeHint: 'Podrá editar el borrador y elegir cómo se le acredita antes de que se envíe nada.',
  needMoreHint: 'Un poco más de detalle primero. El borrador se construye solo con lo que usted escribe aquí.',
  connectError: 'Lo sentimos, no pudimos conectar en este momento. Inténtelo de nuevo.',
  somethingWrong: 'Algo salió mal',
  composeFailed: 'No pudimos redactar su historia',
  editFailed: 'No pudimos hacer ese cambio',
  prepareFailed: 'No pudimos preparar su historia',
  submitFailed: 'No pudimos enviar su historia',
  withdrawFailed: 'No pudimos retirar la historia',
  withdrawn: 'Su historia fue retirada. La campaña ya no puede verla.',

  titleLabel: 'Título',
  optional: '(opcional)',
  yourStory: 'Su historia',
  draftNote: 'Escribimos este borrador con sus respuestas y conservamos sus palabras donde pudimos. Nada de esto viene de otro lugar. Cambie lo que quiera.',
  wantChange: '¿Quiere que hagamos un cambio por usted?',
  describeEdit: 'Describa el cambio y se hace, usando solo lo que usted compartió. No se inventa nada.',
  editPlaceholder: 'p. ej. "Hazla más corta" o "Empieza con la parte sobre mi hijo"',
  makeEdit: 'Hacer el cambio',
  backToQuestions: 'Volver a las preguntas',
  continue: 'Continuar',

  consentTitle: 'Cómo se le acredita y qué permite',
  chooseCredit: 'Elija cómo se le acredita',
  attribution: {
    named: { label: 'Usar mi nombre completo', help: 'Su historia se atribuye a su nombre.' },
    first_name_only: { label: 'Solo mi primer nombre', help: 'Quitamos su apellido antes de enviar la historia.' },
    anonymous: { label: 'Mantenerme en el anonimato', help: 'Quitamos nombres, lugares y otros detalles que identifiquen antes de que la campaña la vea. Usted revisa el resultado primero.' },
  },
  yourFirstName: 'Su primer nombre',
  yourName: 'Su nombre',
  firstNamePlaceholder: 'Primer nombre',
  fullNamePlaceholder: 'Nombre completo',
  keepFirstOnly: 'Si escribe su nombre completo, solo conservamos su primer nombre.',
  yourAddress: 'Su dirección',
  addressOnce: 'Usamos su dirección una sola vez, para confirmar que usted es un constituyente. La calle nunca se comparte ni se guarda. Abajo elige si la campaña ve su ciudad, estado y representantes.',
  shareLocationLabel: 'Compartir mi ciudad, estado y los funcionarios que me representan con esta campaña',
  campaignWillSeeA: 'La campaña verá',
  yourCityState: 'su ciudad y estado',
  campaignWillSeeB: 'y los nombres de sus funcionarios electos, para que pueda llevar su historia a las personas que lo representan.',
  withoutLocation: 'La campaña verá su historia sin ubicación.',
  howMayUse: 'Cómo puede usar su historia esta campaña',
  howMayUseQ: '¿Cómo puede la campaña usar su historia?',
  checkEach: 'Desmarque cualquier uso con el que no se sienta cómodo. La campaña solo puede usar su historia de las formas que queden marcadas. Puede desmarcarlas todas: entonces la campaña puede leerla pero no usarla en otro lugar.',
  usage: {
    shared_with_legislators: { label: 'Compartida con funcionarios electos', description: 'Enviada o mostrada a legisladores y su personal para apoyar la causa.' },
    published_web_social: { label: 'Publicada en la web o en redes sociales', description: 'Publicada en el sitio web o en las redes de la organización.' },
    included_in_reports: { label: 'Citada en informes y materiales', description: 'Usada en informes, presentaciones o materiales impresos.' },
    shared_with_media: { label: 'Compartida con la prensa', description: 'Entregada a periodistas o medios que cubren el tema.' },
    used_in_campaign_messaging: { label: 'Usada en los mensajes de la campaña', description: 'Incluida en los correos, la recaudación de fondos o las campañas de la organización.' },
    contact_me_followup: { label: 'Pueden contactarme al respecto', description: 'La organización puede comunicarse con usted sobre su historia.' },
  },
  contactEmail: 'Correo de contacto',
  emailPlaceholder: 'usted@ejemplo.com',
  sharedOnlyIfTyped: 'Se comparte solo con esta campaña, y solo si lo escribe aquí.',
  shareWith: 'Compartir mi historia con',
  throughDashboard: 'a través de su panel.',
  anonSavedNote: ' No se guarda ningún nombre, contacto ni ubicación con ella.',
  truthful: 'Esta es mi propia experiencia y es verdadera hasta donde sé.',
  adult: 'Tengo 18 años o más, o soy padre, madre o tutor y comparto la experiencia de mi familia.',
  laterSignedIn: 'Puede editar o retirar su historia más tarde desde su panel. Lo que la campaña ya haya usado antes de que la cambie puede no ser totalmente recuperable.',
  laterAnon: 'Después de enviar recibirá un enlace para retirarla en la siguiente pantalla. Guárdelo: sin una cuenta es la única forma de eliminar la historia después. Lo que la campaña ya haya usado antes de eso puede no ser totalmente recuperable.',
  back: 'Atrás',
  checkAnonVersion: 'Revisar la versión anónima',
  submitStory: 'Enviar historia',
  vChooseCredit: 'Elija cómo quiere que se le acredite.',
  vConfirmShare: (headline: string) => `Confirme que quiere compartir su historia con ${headline}.`,
  vConfirmTruthful: 'Confirme que esta es su propia experiencia verdadera.',
  vConfirmAdult: 'Confirme que tiene 18 años o más, o que es padre, madre o tutor y comparte una experiencia familiar.',
  vEnterName: 'Escriba el nombre que quiere que se use, o elija permanecer en el anonimato.',
  vEnterAddress: 'Escriba su dirección. La calle se usa solo para confirmar que es un constituyente y nunca se guarda.',

  previewTitle: 'Esto es lo que recibirá la campaña',
  previewNote: 'Quitamos nombres, lugares y otros detalles que podrían identificarle. Léalo una vez más. Todavía no se ha guardado nada.',
  checkDetails: 'Revise usted mismo estos detalles:',
  anonAria: 'Versión anónima de su historia',
  submitThisVersion: 'Enviar esta versión',

  thankYou: 'Gracias por compartir',
  storyWithdrawn: 'Historia retirada',
  canReadNow: 'La campaña ya puede leer su historia en su panel.',
  canNoLonger: 'La campaña ya no puede verla.',
  unresolved: 'Detalles que no pudimos resolver del todo:',
  copied: 'Copiado',
  copyMyStory: 'Copiar mi historia',
  editFromDashboardA: 'Puede editar o retirar esta historia desde su',
  dashboard: 'panel',
  changedMind: '¿Cambió de opinión? Puede',
  withdrawNow: 'retirarla ahora',
  keepLink: '. Para retirarla más tarde, guarde este enlace:',
  shareText: (headline: string) => `Compartí mi historia con "${headline}". Usted puede compartir la suya aquí:`,
  shareTitle: (headline: string) => `Comparta su historia: ${headline}`,
  sharePrompt: '¿Conoce a alguien con una historia? Envíele el enlace de la campaña.',
  sharesLinkOnly: 'Esto comparte un enlace a la campaña, nunca su historia.',
};

export function storytellerCopy(language: string | null | undefined): StorytellerCopy {
  return language === 'es' ? es : en;
}
