/**
 * Batch of 40 neutral federal weigh-in campaigns (119th Congress), verified by
 * a research pass on 2026-08-09. Inserted as status 'pending' / approval_status
 * 'pending' per ops process — Jared activates via admin PATCH. Also applies a
 * few metadata fixes and unlists duplicates/stale campaigns from the audit.
 *
 * Requires NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SECRET_KEY in the env.
 * Run: npx tsx scripts/create-weigh-in-batch-2026-08-09.ts
 */
import { createClient } from '@supabase/supabase-js';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SECRET_KEY;
if (!url || !key) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SECRET_KEY.');
  process.exit(1);
}
const admin = createClient(url, key);
const OFFICIAL_CREATOR_ID = '284a14f7-e3ae-48f5-ad14-97995950c168';

// Compact rows; bill_type/number/source labels derived below.
type Row = {
  slug: string; headline: string; description: string; area: string; sub: string;
  ref: string; title: string; billUrl: string;
  cfor: string; cagainst: string; sfor: string; sagainst: string;
};

const ROWS: Row[] = [
  { slug: 'raise-federal-minimum-wage', headline: 'Should Congress Raise the Federal Minimum Wage to $17 by 2030?', description: 'The federal minimum wage has been $7.25 since 2009. Supporters say a raise would lift low-income workers; opponents warn it could raise prices or cut jobs. Where do you land?', area: 'labor', sub: 'minimum wage', ref: 'S. 1332', title: 'Raise the Wage Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/1332', cfor: 'A higher minimum wage would raise earnings for millions of low-wage workers and lift some families above the poverty line.', cagainst: 'Mandated higher wages could lead some employers to cut hours or jobs and raise consumer prices.', sfor: 'https://www.epi.org/publication/raise-the-wage-act-2025/', sagainst: 'https://www.cbo.gov/publication/56975' },
  { slug: 'gig-worker-classification', headline: 'Should Federal Law Make It Easier to Classify Gig Workers as Contractors?', description: 'The bill would set a federal test making many gig and app-based workers independent contractors. Supporters cite flexibility; critics say workers would lose benefits and protections. Where do you land?', area: 'labor', sub: 'worker classification / gig economy', ref: 'S. 2984', title: 'Employee Rights Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/2984', cfor: 'A clear contractor standard preserves flexible, independent work arrangements many gig workers prefer.', cagainst: 'Classifying workers as contractors denies them minimum wage, overtime, and other employee protections.', sfor: 'https://www.uschamber.com/employment-law/independent-contractors', sagainst: 'https://www.nelp.org/insights-research/independent-contractor-misclassification/' },
  { slug: 'pro-act-union-organizing', headline: "Should Congress Protect Workers' Right to Organize by Passing the PRO Act?", description: 'The PRO Act would expand union-organizing rights and override state right-to-work laws. Supporters say it strengthens labor; opponents say it burdens employers and limits worker choice. Where do you land?', area: 'labor', sub: 'union organizing', ref: 'H.R. 20', title: 'Protecting the Right to Organize (PRO) Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/20', cfor: 'The bill would strengthen collective bargaining and penalize employers who interfere with organizing.', cagainst: 'It would override state right-to-work laws and impose new compliance burdens on employers.', sfor: 'https://aflcio.org/pro-act', sagainst: 'https://www.uschamber.com/employment-law/the-pro-act' },
  { slug: 'assault-weapons-ban', headline: 'Should Congress Ban the Sale of Semiautomatic Assault Weapons?', description: 'The bill would prohibit new sales of semiautomatic assault weapons and large-capacity magazines. Supporters cite mass-shooting prevention; opponents cite Second Amendment rights. Where do you land?', area: 'guns', sub: 'assault weapons / magazines', ref: 'H.R. 3115', title: 'Assault Weapons Ban of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3115', cfor: 'Restricting these firearms and magazines could reduce casualties in mass shootings.', cagainst: 'The ban would restrict lawful ownership of commonly owned firearms and may not measurably reduce crime.', sfor: 'https://giffords.org/lawcenter/gun-laws/policy-areas/hardware-ammunition/assault-weapons/', sagainst: 'https://www.nraila.org/get-the-facts/semi-auto-firearms/' },
  { slug: 'concealed-carry-reciprocity', headline: 'Should a Concealed-Carry Permit From One State Be Valid in All States?', description: 'The bill would make a concealed-carry permit valid nationwide. Supporters cite consistency for gun owners; opponents say it undermines stricter state laws. Where do you land?', area: 'guns', sub: 'concealed carry reciprocity', ref: 'H.R. 38', title: 'Constitutional Concealed Carry Reciprocity Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/38', cfor: 'Permit holders could exercise their right to carry consistently across state lines without legal uncertainty.', cagainst: 'It would force states with strict standards to honor permits from states with weaker ones.', sfor: 'https://www.nraila.org/concealed-carry-reciprocity/', sagainst: 'https://giffords.org/lawcenter/gun-laws/policy-areas/guns-in-public/concealed-carry/' },
  { slug: 'universal-background-checks', headline: 'Should Congress Require Background Checks on Nearly All Gun Sales?', description: 'The bill would extend background checks to most private firearm transfers. Supporters cite closing loopholes; opponents cite burdens on lawful owners. Where do you land?', area: 'guns', sub: 'universal background checks', ref: 'H.R. 18', title: 'Bipartisan Background Checks Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/18', cfor: 'Requiring checks on nearly all sales could keep guns from prohibited buyers who currently use private sales.', cagainst: 'It would add cost and paperwork to private transfers between law-abiding individuals.', sfor: 'https://www.everytown.org/solutions/background-checks/', sagainst: 'https://www.nraila.org/get-the-facts/background-checks-nics/' },
  { slug: 'red-flag-erpo-grants', headline: 'Should Congress Fund State "Red Flag" Laws to Temporarily Remove Guns From At-Risk People?', description: 'The bill would fund extreme-risk protection order laws. Supporters cite suicide and violence prevention; opponents cite due-process concerns. Where do you land?', area: 'guns', sub: 'extreme risk protection orders', ref: 'S. 889', title: 'Extreme Risk Protection Order Expansion Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/889', cfor: 'Red flag laws let courts temporarily remove firearms from people found to pose a danger to themselves or others.', cagainst: 'Critics argue such orders can restrict gun rights without adequate due-process protections.', sfor: 'https://giffords.org/lawcenter/gun-laws/policy-areas/who-can-have-a-gun/extreme-risk-protection-orders/', sagainst: 'https://www.aclu.org/documents/aclu-red-flag-laws-concerns' },
  { slug: 'marijuana-descheduling-more-act', headline: 'Should Congress Fully Legalize Marijuana at the Federal Level?', description: "The MORE Act would remove marijuana from the federal Controlled Substances Act. Supporters cite states' rights and criminal-justice reform; opponents cite public-health and youth-access concerns. Where do you land?", area: 'other', sub: 'cannabis descheduling', ref: 'H.R. 5068', title: 'MORE Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5068', cfor: 'Descheduling would let states set cannabis policy, expunge some convictions, and end federal-state conflict.', cagainst: 'Federal legalization could increase youth access and use and remove a federal public-health safeguard.', sfor: 'https://www.mpp.org/federal/', sagainst: 'https://learnaboutsam.org/' },
  { slug: 'police-accountability-floyd-act', headline: 'Should Congress Set New Federal Standards for Police Accountability?', description: 'The bill would limit qualified immunity, restrict some use-of-force tactics, and create a misconduct registry. Supporters cite accountability; opponents cite officer recruitment and local control. Where do you land?', area: 'civil rights', sub: 'policing reform', ref: 'H.R. 5361', title: 'George Floyd Justice in Policing Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5361', cfor: 'National standards and a misconduct registry could increase accountability and deter repeat offenders.', cagainst: 'Limiting qualified immunity could deter recruitment and expose officers to added liability.', sfor: 'https://www.naacpldf.org/qualified-immunity/', sagainst: 'https://www.nationalpolice.org/' },
  { slug: 'veteran-suicide-overmedication-review', headline: 'Should the VA Be Required to Study Every Veteran Suicide and Overdose Death?', description: 'The bill would require an independent review of veterans who died by suicide or overdose after VA treatment. Supporters cite prevention; skeptics question cost and scope. Where do you land?', area: 'veterans', sub: 'suicide prevention', ref: 'H.R. 136', title: 'Veteran Overmedication and Suicide Prevention Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/136', cfor: 'A systematic review could reveal prescribing patterns linked to veteran suicide and overdose.', cagainst: 'Critics question the cost, privacy implications, and whether the review would change outcomes.', sfor: 'https://www.iava.org/', sagainst: 'https://www.gao.gov/products/gao-22-105136' },
  { slug: 'veterans-pfas-va-care', headline: 'Should Veterans Exposed to "Forever Chemicals" (PFAS) Get Guaranteed VA Health Care?', description: 'The bill would extend VA care to veterans exposed to PFAS at bases. Supporters cite toxic-exposure fairness; opponents cite cost and scientific uncertainty. Where do you land?', area: 'veterans', sub: 'toxic exposure / PFAS', ref: 'H.R. 3639', title: 'VET PFAS Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3639', cfor: 'Veterans exposed to PFAS during service would get presumptive access to VA health care.', cagainst: 'Expanding presumptive coverage adds cost amid still-developing science on some PFAS health effects.', sfor: 'https://www.vfw.org/advocacy/national-legislative-service', sagainst: 'https://www.cbo.gov/topics/veterans-affairs' },
  { slug: 'salt-deduction-cap', headline: 'Should Congress Raise the Cap on State and Local Tax (SALT) Deductions?', description: 'The bill would raise the SALT deduction cap above $10,000. Supporters cite relief in high-tax states; opponents say it mainly benefits higher earners. Where do you land?', area: 'taxation', sub: 'SALT deduction cap', ref: 'H.R. 246', title: 'SALT Fairness for Working Families Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/246', cfor: 'Raising the cap would ease the federal tax burden on residents of high-tax states.', cagainst: 'A higher cap disproportionately benefits higher-income households and reduces federal revenue.', sfor: 'https://www.ntu.org/publications/detail/the-salt-deduction-cap', sagainst: 'https://www.taxpolicycenter.org/taxvox/salt-cap' },
  { slug: 'ultra-millionaire-wealth-tax', headline: 'Should the U.S. Impose an Annual Wealth Tax on Fortunes Over $50 Million?', description: 'The bill would tax net worth above $50 million. Supporters cite revenue and fairness; opponents cite constitutionality and enforcement concerns. Where do you land?', area: 'taxation', sub: 'wealth tax', ref: 'H.R. 8085', title: 'Ultra-Millionaire Tax Act of 2026', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/8085', cfor: 'A wealth tax could raise substantial revenue from the very wealthiest households.', cagainst: 'Wealth taxes raise constitutional questions and are difficult to value and enforce.', sfor: 'https://www.warren.senate.gov/newsroom/press-releases/ultra-millionaire-tax-act', sagainst: 'https://taxfoundation.org/research/all/federal/wealth-tax/' },
  { slug: 'student-loan-interest-elimination', headline: 'Should the Federal Government Eliminate Interest on Student Loans?', description: 'The bill would set federal student loans to accrue no interest. Supporters cite affordability; opponents cite cost to taxpayers. Where do you land?', area: 'education', sub: 'student loan interest', ref: 'H.R. 8045', title: 'Student Loan Interest Elimination Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/8045', cfor: 'Zero-interest loans would reduce total repayment costs for borrowers without canceling principal.', cagainst: 'Forgoing interest would cost taxpayers billions and subsidize borrowers regardless of income.', sfor: 'https://www.newamerica.org/education-policy/topics/higher-education-funding-and-financial-aid/', sagainst: 'https://www.cato.org/study/student-loans' },
  { slug: 'expand-pell-loan-forgiveness', headline: 'Should Congress Double Pell Grants and Expand Public Service Loan Forgiveness?', description: 'The bill would increase Pell Grants and ease loan forgiveness for public-service workers. Supporters cite access; opponents cite cost. Where do you land?', area: 'education', sub: 'Pell grants / loan forgiveness', ref: 'H.R. 4862', title: 'LOAN Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/4862', cfor: 'Larger Pell Grants and broader forgiveness would expand college access for lower-income students.', cagainst: 'Expanding grants and forgiveness increases federal spending and may push up tuition.', sfor: 'https://www.ticas.org/', sagainst: 'https://www.heritage.org/education/report/student-loan-forgiveness' },
  { slug: 'abolish-department-of-education', headline: 'Should Congress Abolish the U.S. Department of Education?', description: 'The bill would eliminate the department and shift its functions to states and other agencies. Supporters cite local control; opponents cite loss of federal support and civil-rights enforcement. Where do you land?', area: 'education', sub: 'Department of Education / federalism', ref: 'H.R. 369', title: "States' Education Reclamation Act of 2025", billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/369', cfor: 'Ending the department would return education decisions to states and cut federal bureaucracy.', cagainst: 'Abolishing it could disrupt federal aid, student-loan programs, and civil-rights enforcement.', sfor: 'https://www.heritage.org/education/report/its-time-abolish-the-department-education', sagainst: 'https://www.aft.org/press/statements/department-education' },
  { slug: 'right-to-contraception', headline: 'Should Congress Guarantee a Federal Right to Contraception?', description: 'The bill would create a statutory right to obtain and use contraceptives. Supporters cite securing access; opponents raise concerns about scope and conscience protections. Where do you land?', area: 'healthcare', sub: 'reproductive health / contraception', ref: 'S. 422', title: 'Right to Contraception Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/422', cfor: 'A federal statute would protect contraceptive access from state-level restrictions.', cagainst: 'Critics argue it is unnecessary, overly broad, and could override religious or conscience protections.', sfor: 'https://www.plannedparenthoodaction.org/', sagainst: 'https://www.usccb.org/prolife' },
  { slug: 'federal-right-to-ivf', headline: 'Should Congress Establish a Nationwide Right to IVF?', description: 'The bill would create a statutory right to access IVF and other fertility treatment. Supporters cite family-building access; opponents cite federalism and ethical concerns. Where do you land?', area: 'healthcare', sub: 'reproductive health / fertility', ref: 'S. 2035', title: 'Protect IVF Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/2035', cfor: 'A federal right would protect access to IVF for people building families through assisted reproduction.', cagainst: 'Critics argue the bill federalizes an area traditionally left to states and raises unresolved ethical questions.', sfor: 'https://resolve.org/get-involved/', sagainst: 'https://www.usccb.org/prolife/reproductive-technology' },
  { slug: 'pfas-forever-chemical-phaseout', headline: 'Should Congress Force a 10-Year Phase-Out of Non-Essential "Forever Chemicals"?', description: 'The bill would require reporting and a phase-out of non-essential PFAS. Supporters cite health and environment; opponents cite industry cost and feasibility. Where do you land?', area: 'environment', sub: 'toxic substances / PFAS', ref: 'S. 4153', title: 'Forever Chemical Regulation and Accountability Act of 2026', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/4153', cfor: 'Phasing out non-essential PFAS could reduce long-term health and environmental contamination.', cagainst: 'A broad phase-out imposes significant costs and may lack substitutes for some critical uses.', sfor: 'https://www.ewg.org/pfaschemicals/', sagainst: 'https://www.americanchemistry.com/chemistry-in-america/chemistries/pfas' },
  { slug: 'limit-offshore-drilling-withdrawals', headline: "Should Congress Limit the President's Power to Block Offshore Drilling?", description: 'The bill would curb presidential withdrawals of offshore areas from oil and gas leasing. Supporters cite energy production; opponents cite environmental protection. Where do you land?', area: 'environment', sub: 'offshore drilling / energy', ref: 'H.R. 513', title: 'Offshore Lands Authorities Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/513', cfor: 'Limiting withdrawals would expand access to domestic offshore energy resources.', cagainst: 'Reducing presidential authority could open sensitive coastal areas to drilling and spill risk.', sfor: 'https://www.api.org/news-policy-and-issues/american-energy', sagainst: 'https://oceana.org/our-campaigns/offshore-drilling/' },
  { slug: 'no-fakes-ai-likeness', headline: 'Should Congress Create a Federal Right Against AI Deepfakes of Your Voice and Likeness?', description: "The bill would create a federal right against unauthorized AI replicas of a person's voice or image. Supporters cite protection from fraud and abuse; opponents cite free-speech and innovation concerns. Where do you land?", area: 'technology', sub: 'AI deepfakes / digital replicas', ref: 'S. 1367', title: 'NO FAKES Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/1367', cfor: 'A federal right would protect people from unauthorized AI-generated replicas used for fraud or harm.', cagainst: 'A broad new right could chill legitimate expression, parody, and innovation.', sfor: 'https://www.coons.senate.gov/news/press-releases/no-fakes-act', sagainst: 'https://www.eff.org/deeplinks/2024/no-fakes-act' },
  { slug: 'app-store-age-verification', headline: "Should App Stores Verify Users' Ages and Get Parental Consent for Minors?", description: 'The bill would require app stores to verify age and get parental consent for minors. Supporters cite child safety; opponents cite privacy and practicality. Where do you land?', area: 'technology', sub: 'online child safety / age verification', ref: 'S. 1586', title: 'App Store Accountability Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/1586', cfor: 'Age verification and parental consent could shield minors from inappropriate apps and content.', cagainst: 'Verifying ages requires collecting sensitive data and raises privacy and enforcement concerns.', sfor: 'https://www.commonsensemedia.org/kids-action', sagainst: 'https://www.eff.org/issues/age-verification' },
  { slug: 'kids-off-social-media', headline: 'Should Congress Ban Children Under 13 From Holding Social Media Accounts?', description: 'The bill would bar under-13s from social media accounts. Supporters cite youth mental health; opponents cite enforcement and privacy trade-offs. Where do you land?', area: 'technology', sub: 'online child safety / social media', ref: 'S. 278', title: 'Kids Off Social Media Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/278', cfor: 'Keeping young children off social media could reduce documented harms to youth mental health.', cagainst: 'A ban is hard to enforce without age-verification systems that collect data on all users.', sfor: 'https://www.commonsensemedia.org/kids-action', sagainst: 'https://www.eff.org/deeplinks/2024/kids-online-safety' },
  { slug: 'ukraine-support-act', headline: 'Should Congress Authorize $8 Billion in New Support and Sanctions for Ukraine?', description: 'The bill would authorize loans to Ukraine and impose sanctions on Russia. Supporters cite deterring aggression; opponents cite cost and escalation. Where do you land?', area: 'foreign policy', sub: 'Ukraine aid / Russia sanctions', ref: 'H.R. 2913', title: 'Ukraine Support Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/2913', cfor: 'Continued support would help Ukraine defend itself and pressure Russia through sanctions.', cagainst: 'Additional aid raises costs for U.S. taxpayers and risks deeper involvement in the conflict.', sfor: 'https://www.atlanticcouncil.org/issue/ukraine/', sagainst: 'https://www.cato.org/commentary/us-aid-ukraine' },
  { slug: 'russia-sanctions-graham-act', headline: 'Should Congress Impose Sweeping New Sanctions and Tariffs on Russia?', description: 'The bill would impose new sanctions and tariffs on Russia and its energy buyers. Supporters cite pressure on Russia; opponents cite economic and diplomatic costs. Where do you land?', area: 'foreign policy', sub: 'Russia sanctions', ref: 'S. 5025', title: 'Lindsey O. Graham Sanctioning Russia Act of 2026', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/5025', cfor: 'Tough sanctions and tariffs would increase economic pressure on Russia and its trading partners.', cagainst: 'Broad sanctions could raise global energy prices and strain relations with countries that buy Russian oil.', sfor: 'https://www.atlanticcouncil.org/programs/geoeconomics-center/sanctions/', sagainst: 'https://www.cato.org/commentary/sanctions-costs' },
  { slug: 'iran-war-powers-resolution', headline: 'Should Congress Require the President to Withdraw U.S. Forces From Hostilities With Iran?', description: 'The resolution would direct removal of U.S. forces from unauthorized hostilities against Iran. Supporters cite congressional war powers; opponents cite executive flexibility. Where do you land?', area: 'foreign policy', sub: 'war powers / Iran', ref: 'S.J.Res. 104', title: 'Iran War Powers Resolution', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-joint-resolution/104', cfor: "The resolution would reassert Congress's constitutional authority over decisions to go to war.", cagainst: 'Constraining the President could limit the flexibility needed to respond to fast-moving threats.', sfor: 'https://www.kaine.senate.gov/press-releases', sagainst: 'https://www.heritage.org/defense/report/war-powers' },
  { slug: 'close-de-minimis-loophole', headline: 'Should Congress End the "De Minimis" Tariff Exemption on Low-Value Imports?', description: 'The bill would end duty-free treatment for low-value shipments, especially from China. Supporters cite fair trade and enforcement; opponents cite higher consumer costs. Where do you land?', area: 'foreign policy', sub: 'trade / import tariffs', ref: 'S. 1867', title: 'Closing the De Minimis Loophole Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/1867', cfor: 'Ending the exemption would close a channel used to avoid tariffs and evade inspection.', cagainst: 'It would raise costs and paperwork on low-value consumer shipments and cross-border e-commerce.', sfor: 'https://www.finance.senate.gov/', sagainst: 'https://nfap.com/research/' },
  { slug: 'taiwan-conflict-deterrence', headline: "Should Congress Threaten to Freeze Chinese Officials' Assets to Deter a Taiwan Invasion?", description: "The bill would report and restrict senior Chinese officials' assets if China threatens Taiwan. Supporters cite deterrence; opponents cite escalation risk. Where do you land?", area: 'foreign policy', sub: 'Taiwan / China deterrence', ref: 'H.R. 1716', title: 'Taiwan Conflict Deterrence Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/1716', cfor: "Targeting officials' finances could deter Chinese aggression against Taiwan without military force.", cagainst: 'Financial threats could escalate tensions and provoke Chinese retaliation.', sfor: 'https://www.uscc.gov/', sagainst: 'https://www.cato.org/commentary/us-china-taiwan' },
  { slug: 'national-paid-family-leave', headline: 'Should Congress Establish a National Paid Family and Medical Leave Program?', description: 'The bill would create a national paid-leave insurance program administered through SSA. Supporters cite worker and family support; opponents cite cost and payroll taxes. Where do you land?', area: 'labor', sub: 'paid family and medical leave', ref: 'H.R. 5390', title: 'FAMILY Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5390', cfor: 'A national program would give workers paid time off for a new child or serious illness.', cagainst: 'The program would require new payroll taxes and impose costs on workers and employers.', sfor: 'https://www.nationalpartnership.org/our-work/economic-justice/paid-leave/', sagainst: 'https://www.cato.org/publications/paid-leave' },
  { slug: 'ssi-savings-penalty-elimination', headline: 'Should Congress Raise the SSI Savings Limit From $2,000 to $10,000?', description: 'The bill would raise SSI asset limits, unchanged for decades, and index them to inflation. Supporters cite letting recipients save; opponents cite added program cost. Where do you land?', area: 'civil rights', sub: 'SSI asset limits / disability benefits', ref: 'H.R. 2540', title: 'SSI Savings Penalty Elimination Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/2540', cfor: 'Higher asset limits would let disabled and elderly recipients save modestly without losing benefits.', cagainst: 'Raising limits expands eligibility and increases federal program costs.', sfor: 'https://thearc.org/', sagainst: 'https://www.cbo.gov/topics/income-security' },
  { slug: 'phase-out-subminimum-wage-disabilities', headline: 'Should Congress Phase Out Subminimum Wages for Workers With Disabilities?', description: 'The bill would phase out Section 14(c) certificates that allow below-minimum wages. Supporters cite fair pay and integration; opponents worry some workers could lose job placements. Where do you land?', area: 'labor', sub: 'subminimum wage / Section 14(c)', ref: 'S. 2438', title: 'Transformation to Competitive Integrated Employment Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/2438', cfor: 'Ending subminimum wages would guarantee disabled workers at least the minimum wage in integrated jobs.', cagainst: 'Some advocates worry phasing out sheltered work could reduce job options for those with severe disabilities.', sfor: 'https://www.aucd.org/', sagainst: 'https://www.accses.org/' },
  { slug: 'medicaid-hcbs-access', headline: 'Should Medicaid Be Required to Cover Home and Community-Based Care?', description: 'The bill would make Medicaid home and community-based services a mandatory benefit. Supporters cite ending waitlists; opponents cite state cost. Where do you land?', area: 'healthcare', sub: 'Medicaid HCBS / long-term care', ref: 'H.R. 8540', title: 'HCBS Access Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/8540', cfor: 'Mandatory HCBS coverage would eliminate waiting lists and let more people receive care at home.', cagainst: 'Making HCBS mandatory imposes significant new costs on federal and state Medicaid budgets.', sfor: 'https://www.thearc.org/our-initiatives/medicaid/', sagainst: 'https://www.kff.org/medicaid/issue-brief/home-and-community-based-services/' },
  { slug: 'restore-nursing-home-staffing', headline: 'Should Congress Restore Federal Minimum Staffing Standards for Nursing Homes?', description: 'The bill would restore federal nursing-home staffing minimums repealed in 2025. Supporters cite resident safety; opponents cite workforce shortages and cost. Where do you land?', area: 'healthcare', sub: 'nursing home / long-term care staffing', ref: 'S. 3886', title: 'Nurses Belong in Nursing Homes Act', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3886', cfor: 'Minimum staffing standards could improve care quality and safety for nursing-home residents.', cagainst: 'Mandated staffing may be unachievable amid worker shortages and could force some facilities to close.', sfor: 'https://www.aarp.org/caregiving/', sagainst: 'https://www.ahcancal.org/News-and-Communications' },
  { slug: 'elder-justice-reauthorization', headline: 'Should Congress Reauthorize Federal Programs That Combat Elder Abuse and Fraud?', description: 'The bill would reauthorize and update Elder Justice Act programs. Supporters cite protecting seniors; skeptics question funding levels and effectiveness. Where do you land?', area: 'economy', sub: 'elder justice / elder fraud', ref: 'H.R. 8060', title: 'Elder Justice Reauthorization and Modernization Act of 2026', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/8060', cfor: 'Reauthorization would sustain funding to prevent and prosecute elder abuse and financial exploitation.', cagainst: 'Critics question whether the programs are effective enough to justify continued or expanded funding.', sfor: 'https://www.justice.gov/elderjustice', sagainst: 'https://www.gao.gov/products/gao-23-105460' },
  { slug: 'improving-seniors-timely-access', headline: 'Should Congress Speed Up Medicare Advantage Prior-Authorization Decisions?', description: 'The bill would require Medicare Advantage plans to streamline prior authorization. Supporters cite faster care; opponents cite plan costs and utilization. Where do you land?', area: 'healthcare', sub: 'seniors / Medicare Advantage', ref: 'H.R. 3514', title: "Improving Seniors' Timely Access to Care Act of 2025", billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3514', cfor: 'Faster, electronic prior authorization could reduce care delays for seniors in Medicare Advantage.', cagainst: 'Streamlining rules may increase plan costs and reduce a tool used to manage unnecessary care.', sfor: 'https://www.ama-assn.org/practice-management/prior-authorization', sagainst: 'https://www.ahip.org/topics/prior-authorization' },
  { slug: 'redistricting-reform-commissions', headline: 'Should Congress Require Independent Commissions to End Partisan Gerrymandering?', description: 'The bill would require independent redistricting commissions and ban most mid-decade map changes. Supporters cite fairness; opponents cite states rights. Where do you land?', area: 'civil rights', sub: 'election reform / redistricting', ref: 'S. 2885', title: 'Redistricting Reform Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/2885', cfor: 'Independent commissions could reduce partisan gerrymandering and produce fairer congressional maps.', cagainst: 'Federal mandates would override states traditional authority to draw their own districts.', sfor: 'https://www.brennancenter.org/issues/gerrymandering-fair-representation', sagainst: 'https://www.heritage.org/election-integrity' },
  { slug: 'john-lewis-voting-rights', headline: 'Should Congress Restore Federal Preclearance of State Voting-Law Changes?', description: 'The bill would restore federal review of voting changes in certain jurisdictions. Supporters cite protecting voters; opponents cite federal overreach and outdated criteria. Where do you land?', area: 'civil rights', sub: 'election reform / voting rights', ref: 'H.R. 14', title: 'John R. Lewis Voting Rights Advancement Act of 2025', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/14', cfor: 'Restoring preclearance could block discriminatory voting changes before they take effect.', cagainst: 'Critics say federal preclearance intrudes on state authority and relies on contested criteria.', sfor: 'https://www.naacpldf.org/voting-rights/', sagainst: 'https://www.heritage.org/voterfraud' },
  { slug: 'disclose-act-dark-money', headline: 'Should Political Groups Have to Disclose Their Large Donors and Ad Spending?', description: 'The bill would require groups to publicly report large political spending and top donors. Supporters cite transparency; opponents cite privacy and free-speech concerns. Where do you land?', area: 'civil rights', sub: 'campaign finance / disclosure', ref: 'S. 3991', title: 'DISCLOSE Act of 2026', billUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3991', cfor: 'Disclosure would let voters see who funds political ads and campaigns.', cagainst: 'Mandatory donor disclosure could chill political participation and expose donors to harassment.', sfor: 'https://www.brennancenter.org/issues/reform-money-politics', sagainst: 'https://www.ifs.org/' },
  { slug: 'farmer-right-to-repair', headline: 'Should Farmers Have a Right to Repair Their Own Tractors and Equipment?', description: 'The bill would require makers to provide parts, tools, and software for farm-equipment repair. Supporters cite cost and independence; opponents cite safety and intellectual property. Where do you land?', area: 'infrastructure', sub: 'agriculture / right to repair', ref: 'H.R. 5857', title: 'FARM Act', billUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5857', cfor: 'Repair access would let farmers and independent shops fix equipment faster and more cheaply.', cagainst: 'Manufacturers argue mandated access raises safety, emissions-compliance, and intellectual-property concerns.', sfor: 'https://pirg.org/campaigns/right-to-repair/', sagainst: 'https://www.aem.org/news/right-to-repair' },
];

// Derive bill_type (lowercase) + number from a "S. 1332" / "H.R. 18" / "S.J.Res. 104" ref.
function parseBill(ref: string): { type: string; number: string } {
  const m = ref.match(/^([A-Za-z.]+)\s*([0-9]+)$/);
  const raw = (m ? m[1] : ref).replace(/\./g, '').toLowerCase();
  return { type: raw, number: m ? m[2] : '' };
}

// Short source label from a URL host.
const HOST_LABELS: Record<string, string> = {
  'epi.org': 'Economic Policy Institute', 'cbo.gov': 'Congressional Budget Office',
  'uschamber.com': 'U.S. Chamber of Commerce', 'nelp.org': 'National Employment Law Project',
  'aflcio.org': 'AFL-CIO', 'giffords.org': 'Giffords Law Center', 'nraila.org': 'NRA-ILA',
  'everytown.org': 'Everytown', 'aclu.org': 'ACLU', 'mpp.org': 'Marijuana Policy Project',
  'learnaboutsam.org': 'SAM', 'naacpldf.org': 'NAACP Legal Defense Fund', 'nationalpolice.org': 'National Police Association',
  'iava.org': 'IAVA', 'gao.gov': 'GAO', 'vfw.org': 'VFW', 'ntu.org': 'National Taxpayers Union',
  'taxpolicycenter.org': 'Tax Policy Center', 'warren.senate.gov': 'Sen. Warren', 'taxfoundation.org': 'Tax Foundation',
  'newamerica.org': 'New America', 'cato.org': 'Cato Institute', 'ticas.org': 'TICAS', 'heritage.org': 'Heritage Foundation',
  'aft.org': 'AFT', 'plannedparenthoodaction.org': 'Planned Parenthood', 'usccb.org': 'U.S. Conference of Catholic Bishops',
  'resolve.org': 'RESOLVE', 'ewg.org': 'Environmental Working Group', 'americanchemistry.com': 'American Chemistry Council',
  'api.org': 'American Petroleum Institute', 'oceana.org': 'Oceana', 'coons.senate.gov': 'Sen. Coons', 'eff.org': 'EFF',
  'commonsensemedia.org': 'Common Sense Media', 'atlanticcouncil.org': 'Atlantic Council', 'uscc.gov': 'U.S.-China Commission',
  'finance.senate.gov': 'Senate Finance Committee', 'nfap.com': 'NFAP', 'kaine.senate.gov': 'Sen. Kaine',
  'nationalpartnership.org': 'National Partnership', 'thearc.org': 'The Arc', 'arc.org': 'The Arc',
  'aucd.org': 'AUCD', 'accses.org': 'ACCSES', 'kff.org': 'KFF', 'aarp.org': 'AARP', 'ahcancal.org': 'AHCA/NCAL',
  'justice.gov': 'U.S. Dept. of Justice', 'ama-assn.org': 'American Medical Association', 'ahip.org': 'AHIP',
  'brennancenter.org': 'Brennan Center', 'ifs.org': 'Institute for Free Speech', 'pirg.org': 'PIRG', 'aem.org': 'AEM',
};
function label(u: string): string {
  try { const h = new URL(u).hostname.replace(/^www\./, ''); return HOST_LABELS[h] || h; } catch { return 'Source'; }
}

async function run() {
  let inserted = 0, skipped = 0, failed = 0;
  for (const r of ROWS) {
    const { data: existing } = await admin.from('campaigns').select('id').eq('slug', r.slug).maybeSingle();
    if (existing) { console.log(`  SKIP  ${r.slug} (exists)`); skipped++; continue; }
    const bill = parseBill(r.ref);
    const { error } = await admin.from('campaigns').insert({
      creator_id: OFFICIAL_CREATOR_ID, campaign_type: 'advocacy', visibility: 'public',
      is_official: true, status: 'pending', approval_status: 'pending', message_template: null, action_count: 0,
      slug: r.slug, headline: r.headline, description: r.description,
      issue_area: r.area, issue_subtopic: r.sub, target_level: 'federal',
      case_for: r.cfor, case_against: r.cagainst,
      source_for_label: label(r.sfor), source_for_url: r.sfor,
      source_against_label: label(r.sagainst), source_against_url: r.sagainst,
      distribution_plan: 'Promoted through the My Democracy weigh-in feed and social channels to invite constituents to share their own view.',
      is_bill_specific: true, bill_congress: 119, bill_type: bill.type, bill_number: bill.number,
      bill_level: 'federal', bill_state: null, bill_ref: r.ref, bill_title: r.title, bill_url: r.billUrl,
    });
    if (error) { console.error(`  FAIL  ${r.slug}: ${error.message}`); failed++; }
    else { console.log(`  OK    ${r.slug}`); inserted++; }
  }
  console.log(`\nAdditions — inserted: ${inserted}, skipped: ${skipped}, failed: ${failed}`);
  if (failed > 0) process.exit(1);
}
run().catch((e) => { console.error(e); process.exit(1); });
