-- Generated from user's neutralize-bill-language.mjs (2026-07-09).
begin;
update campaigns set description = 'Cryptocurrency has grown into a major market, but the U.S. still hasn''t settled the basics: which agency should oversee digital assets, how stablecoins should be backed, and how much consumer protection is enough. Some want clear federal rules; others favor a lighter touch or applying existing law. Where do you stand?', updated_at = now() where slug = 'how-should-us-regulate-crypto-cr7m2x';
update campaigns set description = 'Should the largest online platforms be barred from ranking their own products ahead of competitors'', using business customers'' data against them, or blocking data portability? Supporters call such limits fair competition; opponents call them government micromanagement. Where do you stand?', updated_at = now() where slug = 'big-tech-self-preferencing-tp8n3v';
update campaigns set description = 'The U.S. is short millions of affordable homes, and rents and prices have outpaced incomes. Some favor federal incentives to build more; others favor cutting regulations or leaving it to states and localities. Where do you land?', updated_at = now() where slug = 'tackle-the-housing-shortage-hs5r2k';
update campaigns set description = 'Enhanced Affordable Care Act premium subsidies expired at the start of 2026, and marketplace premiums are rising sharply for many enrollees. Some want Congress to extend the subsidies to keep coverage affordable; others point to the cost and question their design. Where do you land?', updated_at = now() where slug = 'protect-healthcare-restore-aca-subsidies';
update campaigns set description = 'The Constitution gives Congress power over tariffs, but recent presidents have set many through executive authority — reviving a long debate over who should control trade policy, and over tariffs themselves. Some want Congress to reassert control; others say the executive needs flexibility to act fast. Where do you stand?', updated_at = now() where slug = 'demand-a-vote-on-tariffs-7p3q8w';
update campaigns set description = 'Building power lines, pipelines, and energy projects can take a decade under current permitting rules. Some want to streamline approvals to add capacity and lower costs; critics worry that speeding things up weakens environmental and community review. Where do you stand?', updated_at = now() where slug = 'build-energy-projects-faster-ep6m4z';
commit;
